export const FIELD_SYNONYMS: Record<string, string[]> = {
  name: ['name', 'customer name', 'company name', 'full name', 'client name', 'business name', 'vendor name', 'item name', 'account name', 'employee name', 'rate name'],
  email: ['email', 'email address', 'e mail', 'mail'],
  phone: ['phone', 'phone number', 'mobile', 'tel', 'telephone', 'contact number'],
  address: ['address', 'street address', 'street', 'billing address'],
  city: ['city', 'town'],
  country: ['country', 'nation'],
  taxId: ['tax id', 'taxid', 'vat', 'vat number', 'trn', 'tax number', 'tin'],
  creditLimit: ['credit limit', 'credit', 'limit'],
  paymentTerms: ['payment terms', 'terms', 'payment days', 'net days'],
  isActive: ['active', 'is active', 'enabled', 'status'],
  isDefault: ['default', 'is default', 'primary'],
  customerNo: ['customer no', 'customer number', 'customer id', 'id', 'number'],
  vendorNo: ['vendor no', 'vendor number', 'supplier no', 'supplier number'],
  itemCode: ['item code', 'sku', 'product code', 'code', 'item no', 'item number'],
  description: ['description', 'desc', 'notes', 'details'],
  category: ['category', 'group', 'type'],
  unit: ['unit', 'uom', 'unit of measure'],
  costPrice: ['cost price', 'cost', 'purchase price', 'unit cost'],
  salePrice: ['sale price', 'selling price', 'price', 'unit price'],
  quantity: ['quantity', 'qty', 'stock', 'on hand'],
  minQuantity: ['min quantity', 'minimum quantity', 'reorder level', 'min stock'],
  accountNo: ['account no', 'account number', 'account code', 'gl code', 'code'],
  fullName: ['full name', 'account full name', 'long name'],
  parentNo: ['parent no', 'parent account', 'parent account no', 'parent code'],
  accountType: ['account type', 'type', 'gl type'],
  subType: ['sub type', 'subtype', 'detail type'],
  code: ['code', 'cost center code', 'center code'],
  type: ['type', 'cost center type', 'tax type'],
  department: ['department', 'dept', 'division'],
  position: ['position', 'job title', 'title', 'role'],
  joiningDate: ['joining date', 'join date', 'start date', 'hire date', 'date joined'],
  salary: ['salary', 'pay', 'wage', 'compensation', 'monthly salary'],
  salaryType: ['salary type', 'pay type', 'pay frequency'],
  bankAccount: ['bank account', 'iban', 'account number', 'bank'],
  employeeNo: ['employee no', 'employee number', 'emp no', 'staff id'],
  rate: ['rate', 'tax rate', 'percentage', 'percent', 'vat rate'],
}

export function getSynonymsForField(fieldKey: string): string[] {
  return FIELD_SYNONYMS[fieldKey] ?? [fieldKey.replace(/([A-Z])/g, ' $1').trim().toLowerCase()]
}
