import 'server-only'
import { postSourceDocumentToLedger, type PostingLine } from '@/lib/accounting/posting-service'
import { createAdminClient } from '@/lib/supabase/admin'

export async function recordBankTransaction(input:{companyId:string;bankAccountId:string;transactionDate:Date;description:string;reference?:string|null;amount:number;type:'DEBIT'|'CREDIT';status?:string;paymentId?:string|null;sourceType?:string|null;sourceId?:string|null;importedFrom?:string|null;externalDocumentNo?:string|null;externalAccountSourceId?:string|null;sourcePayloadHash?:string|null}) {
  const amount=Math.abs(input.amount); if(!Number.isFinite(amount)||amount<=0) throw new Error('Bank transaction amount must be positive')
  const db=createAdminClient()
  if(input.sourceType&&input.sourceId) {
    const existing=await db.from('bank_transactions').select('*').eq('company_id',input.companyId).eq('source_type',input.sourceType).eq('source_id',input.sourceId).maybeSingle()
    if(existing.error) throw existing.error
    if(existing.data){const coreExact=String(existing.data.bank_account_id)===input.bankAccountId&&Number(existing.data.amount)===amount&&String(existing.data.type)===input.type&&new Date(String(existing.data.transaction_date)).getTime()===input.transactionDate.getTime(),storedHash=String(existing.data.source_payload_hash??''),hashExact=!input.sourcePayloadHash||!storedHash||storedHash===input.sourcePayloadHash;if(!coreExact||!hashExact)throw new Error(`${input.sourceType} ${input.sourceId} changed after materialization; resolve the synchronization conflict.`);if(input.sourcePayloadHash&&!storedHash){const adopted=await db.from('bank_transactions').update({source_payload_hash:input.sourcePayloadHash,external_document_no:input.externalDocumentNo??existing.data.external_document_no,external_account_source_id:input.externalAccountSourceId??existing.data.external_account_source_id}).eq('company_id',input.companyId).eq('id',existing.data.id);if(adopted.error)throw adopted.error}return {...existing.data,source_payload_hash:input.sourcePayloadHash??existing.data.source_payload_hash,_idempotent:true}}
  }
  const account=await db.from('bank_accounts').select('current_balance').eq('company_id',input.companyId).eq('id',input.bankAccountId).is('deleted_at',null).single(); if(account.error) throw account.error
  const created=await db.from('bank_transactions').insert({company_id:input.companyId,bank_account_id:input.bankAccountId,transaction_date:input.transactionDate.toISOString(),description:input.description,reference:input.reference??null,amount,type:input.type,status:input.status??'UNMATCHED',payment_id:input.paymentId??null,source_type:input.sourceType??null,source_id:input.sourceId??null,imported_from:input.importedFrom??null,external_document_no:input.externalDocumentNo??null,external_account_source_id:input.externalAccountSourceId??null,source_payload_hash:input.sourcePayloadHash??null}).select('*, bank_account:bank_accounts(name,currency)').single(); if(created.error) throw created.error
  const delta=input.type==='CREDIT'?amount:-amount
  const updated=await db.from('bank_accounts').update({current_balance:Number(account.data.current_balance)+delta,updated_at:new Date().toISOString()}).eq('company_id',input.companyId).eq('id',input.bankAccountId); if(updated.error) throw updated.error
  return created.data
}

export interface BankDepositAllocation {paymentId?:string|null;accountId:string;amount:number;currency:string;exchangeRate?:number|null;sourceDepositId:string;sourceLineKey:string;sourceTransactionType?:string|null;sourceTransactionId?:string|null;sourceAccountId?:string|null;sourceEntityId?:string|null;metadata?:Record<string,unknown>}
export async function createBankDeposit(input:{companyId:string;userId?:string|null;sourceId:string;bankAccountId:string;date:Date;amount:number;reference?:string|null;description:string;offsetLines:PostingLine[];currency?:string;exchangeRate?:number|null;allocations?:BankDepositAllocation[];externalAccountSourceId?:string|null;sourcePayloadHash?:string|null}) {
  const db=createAdminClient(); const bank=await db.from('bank_accounts').select('account_id,currency').eq('company_id',input.companyId).eq('id',input.bankAccountId).single(); if(bank.error) throw bank.error
  const transaction=await recordBankTransaction({companyId:input.companyId,bankAccountId:input.bankAccountId,transactionDate:input.date,description:input.description,reference:input.reference,amount:input.amount,type:'CREDIT',status:'MATCHED',sourceType:'QUICKBOOKS_DEPOSIT',sourceId:input.sourceId,importedFrom:'quickbooks',externalDocumentNo:input.reference,externalAccountSourceId:input.externalAccountSourceId,sourcePayloadHash:input.sourcePayloadHash})
  if(input.allocations){const replaced=await db.rpc('replace_deposit_allocations',{p_company_id:input.companyId,p_bank_transaction_id:String(transaction.id),p_allocations:input.allocations.map(item=>({payment_id:item.paymentId??null,account_id:item.accountId,amount:item.amount,currency:item.currency,exchange_rate:item.exchangeRate??null,source_deposit_id:item.sourceDepositId,source_line_key:item.sourceLineKey,source_transaction_type:item.sourceTransactionType??null,source_transaction_id:item.sourceTransactionId??null,source_account_id:item.sourceAccountId??null,source_entity_id:item.sourceEntityId??null,metadata:item.metadata??{}}))});if(replaced.error)throw replaced.error}
  if(bank.data.account_id) await postSourceDocumentToLedger({companyId:input.companyId,sourceType:'DEPOSIT',sourceId:String(transaction.id),entryDate:input.date,description:input.description,currency:input.currency??String(bank.data.currency??'SAR'),lines:[{accountId:String(bank.data.account_id),debit:input.amount,description:input.description,exchangeRateOverride:input.exchangeRate},...input.offsetLines],userId:input.userId,reason:'QuickBooks deposit migration'})
  const audit=await db.from('deposit_audit_log').insert({company_id:input.companyId,bank_transaction_id:transaction.id,source_deposit_id:input.sourceId,action:transaction._idempotent?'REIMPORT_VERIFIED':'MATERIALIZED',details:{amount:input.amount,allocationCount:input.allocations?.length??0,bankAccountId:input.bankAccountId,sourcePayloadHash:input.sourcePayloadHash},created_by_id:input.userId??null});if(audit.error)throw audit.error
  return transaction
}
