import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { extractQuickBooksPaymentRelationships } from '../../src/lib/import-export/quickbooks/payment-relationships'

test('a BillPayment preserves a partial Vendor Credit application to one Bill',()=>{const result=extractQuickBooksPaymentRelationships({TotalAmt:70,UnappliedAmt:0,Line:[{Amount:100,LinkedTxn:[{TxnType:'Bill',TxnId:'BILL-1'},{TxnType:'VendorCredit',TxnId:'VC-1'}]}]},'VENDOR');assert.equal(result.issues.length,0);assert.equal(result.allocations[0].cashAmount,70);assert.equal(result.allocations[0].creditAmount,30);assert.deepEqual(result.allocations[0].creditSourceIds,['VC-1'])})

test('one Vendor Credit can be partially applied across multiple Bills',()=>{const first=extractQuickBooksPaymentRelationships({TotalAmt:0,Line:[{Amount:25,LinkedTxn:[{TxnType:'Bill',TxnId:'BILL-1'},{TxnType:'VendorCredit',TxnId:'VC-1'}]}]},'VENDOR'),second=extractQuickBooksPaymentRelationships({TotalAmt:0,Line:[{Amount:35,LinkedTxn:[{TxnType:'Bill',TxnId:'BILL-2'},{TxnType:'VendorCredit',TxnId:'VC-1'}]}]},'VENDOR');assert.equal(first.allocations[0].creditAmount,25);assert.equal(second.allocations[0].creditAmount,35);assert.equal(100-first.creditAppliedAmount-second.creditAppliedAmount,40)})

test('Vendor Credit application schema is normalized, atomic, and prevents over-application',()=>{const sql=readFileSync('supabase/migrations/058_vendor_credit_materialization.sql','utf8');assert.match(sql,/CREATE TABLE public\.vendor_credit_applications/);assert.match(sql,/payment_allocation_id UUID NOT NULL/);assert.match(sql,/materialize_vendor_credit_application/);assert.match(sql,/FOR UPDATE/);assert.match(sql,/Vendor credit is applied above its total/);assert.match(sql,/Vendor credit and bill must belong to the same vendor/);assert.match(sql,/application currency must match/);assert.match(sql,/ON DELETE CASCADE/)})

test('Vendor Credit documents preserve native lines and QuickBooks relationships',()=>{const sql=readFileSync('supabase/migrations/058_vendor_credit_materialization.sql','utf8'),adapter=readFileSync('src/lib/import-export/sources/quickbooks.adapter.ts','utf8'),importer=readFileSync('src/lib/import-export/registry/modules/transactions.module.ts','utf8');assert.match(sql,/CREATE TABLE public\.vendor_credit_lines/);for(const field of ['source_account_id','source_item_id','source_class_id','source_tax_code_id'])assert.match(sql,new RegExp(field));assert.match(adapter,/ItemBasedExpenseLineDetail/);assert.match(adapter,/apAccountSourceId/);assert.match(importer,/lineTable:'vendor_credit_lines'/);assert.match(importer,/resolveVendorCreditLineAccount/)})

test('Vendor Credit posting reduces AP and reverses expense, inventory, and purchase tax',()=>{const posting=readFileSync('src/lib/accounting/document-posting.ts','utf8');assert.match(posting,/postVendorCreditToLedger/);assert.match(posting,/sourceType:'SUPPLIER_CREDIT'/);assert.match(posting,/accountId:apAccount,debit:total/);assert.match(posting,/lines\.push\(\{accountId,credit:Number\(line\.amount\)/);assert.match(posting,/documentType:'VENDOR_CREDIT'/);assert.match(posting,/debit:line\.credit,credit:line\.debit/)})

test('inventory supplier returns are historical and exactly idempotent per document line',()=>{const hook=readFileSync('src/lib/inventory/document-hooks.ts','utf8'),sql=readFileSync('supabase/migrations/058_vendor_credit_materialization.sql','utf8');assert.match(hook,/postGoodsReturnToVendorFromCredit/);assert.match(hook,/movementType:'GOODS_ISSUE'/);assert.match(hook,/postCogsJournal:false/);assert.match(hook,/movementDate:new Date/);assert.match(hook,/\.eq\('reference',reference\)/);assert.match(sql,/stock_movements_source_line_uniq/)})

test('the accounting materializer no longer classifies Vendor Credits as manual-only',()=>{const source=readFileSync('src/lib/import-export/quickbooks/accounting-materializer.ts','utf8');assert.match(source,/'vendor-credits':\{[^\n]*post:postVendorCreditToLedger/);assert.match(source,/'vendor-credits':\{[^\n]*checksInventory:true/);assert.doesNotMatch(source,/vendor credits do not retain source lines/)})

test('exact Vendor Credit re-imports are no-ops and changed posted documents conflict',()=>{const source=readFileSync('src/lib/import-export/registry/modules/transactions.module.ts','utf8'),sql=readFileSync('supabase/migrations/058_vendor_credit_materialization.sql','utf8');assert.match(source,/vendorCreditSourceMatches/);assert.match(source,/source_payload_hash/);assert.match(source,/Resolve the conflict instead of rewriting ledger history/);assert.match(sql,/vendor_credits_legacy_source_uniq/);assert.match(sql,/source_payload_hash=record\.payload_hash/)})

test('certification compares Vendor Credit totals, applications, AP, tax, lines, and inventory',()=>{const source=readFileSync('src/lib/quickbooks-certification/vendor-credits.ts','utf8'),service=readFileSync('src/lib/quickbooks-certification/service.ts','utf8');for(const evidence of ['applied','balance','sourceRelationships','apReduction','inventory return','TxnTaxDetail'])assert.match(source,new RegExp(evidence));assert.match(service,/certifyVendorCredits/);assert.match(service,/vendor-credit-reconciliation/)})

test('posted Vendor Credits are immutable through the native API',()=>{const route=readFileSync('src/app/api/vendor-credits/[id]/route.ts','utf8');assert.match(route,/Posted Vendor Credits are immutable/);assert.match(route,/source_type','SUPPLIER_CREDIT/);assert.match(route,/Total cannot be lower than the amount already applied/)})

test('Vendor Credit accounting remains balanced after tax and application',()=>{const subtotal=100,tax=15,total=115,application=40,remaining=total-application,apDebit=total,expenseCredit=subtotal,taxCredit=tax;assert.equal(apDebit,expenseCredit+taxCredit);assert.equal(application+remaining,total);assert.equal(remaining,75)})
