import assert from 'node:assert/strict'
import test from 'node:test'
import { compareSnapshots, validateCrossReportIntegrity } from '../../src/lib/quickbooks-certification/engine'
import { buildQuickBooksReportRequest, normalizeQuickBooksReport } from '../../src/lib/quickbooks-certification/quickbooks-reports'
import type { CertificationParameters, FinancialReportSnapshot } from '../../src/lib/quickbooks-certification/types'

const parameters:CertificationParameters={startDate:'2026-01-01',endDate:'2026-12-31',asOfDate:'2026-12-31',accountingBasis:'Accrual',homeCurrency:'USD',multiCurrency:false,exact:false,absoluteTolerance:0.01,relativeTolerance:0}
const snapshot=(rows:FinancialReportSnapshot['rows'],reportKey:FinancialReportSnapshot['reportKey']='trial-balance'):FinancialReportSnapshot=>({reportKey,parameters,currency:'USD',rows,totals:rows.reduce<Record<string,number>>((totals,current)=>{for(const [key,value] of Object.entries(current.values))totals[key]=(totals[key]??0)+value;return totals},{})})

test('QuickBooks certification requests preserve the accounting parameters',()=>{const request=buildQuickBooksReportRequest('profit-loss',{...parameters,classIds:['1','2'],departmentIds:['3'],customerIds:['4'],vendorIds:['5']});assert.equal(request.reportName,'ProfitAndLoss');assert.deepEqual(request.parameters,{start_date:'2026-01-01',end_date:'2026-12-31',accounting_method:'Accrual',currency:'USD',class:'1,2',department:'3',customer:'4',vendor:'5'})})

test('QuickBooks report rows normalize nested sections and accounting values',()=>{const result=normalizeQuickBooksReport('trial-balance',{Columns:{Column:[{ColTitle:'Account'},{ColTitle:'Debit'},{ColTitle:'Credit'}]},Rows:{Row:[{Header:{ColData:[{value:'Assets'}]},Rows:{Row:[{ColData:[{value:'Cash',id:'10'},{value:'1,250.00'},{value:'(20.00)'}]}]}}]}},parameters);assert.equal(result.rows.length,1);assert.equal(result.rows[0].key,'cash');assert.deepEqual(result.rows[0].values,{debit:1250,credit:-20});assert.equal(result.rows[0].sourceRefs?.[0].sourceId,'10')})

test('exact certification fails any difference and returns drill-down evidence',()=>{const qb=snapshot([{key:'cash',label:'Cash',values:{ending_balance:100}}]);const hisab=snapshot([{key:'cash',label:'Cash',values:{ending_balance:99.99},sourceRefs:[{sourceType:'PAYMENT',sourceId:'local-1'}]}]);const result=compareSnapshots({quickBooks:{...qb,parameters:{...parameters,exact:true,absoluteTolerance:0}},hisab});assert.equal(result.status,'FAILED');assert.equal(result.differences[0].difference,-0.01);assert.equal(result.differences[0].sourceRefs?.[0].sourceId,'local-1')})

test('materiality creates a warning but never hides the difference',()=>{const qb=snapshot([{key:'cash',label:'Cash',values:{ending_balance:100}}]);const hisab=snapshot([{key:'cash',label:'Cash',values:{ending_balance:100.005}}]);const result=compareSnapshots({quickBooks:qb,hisab});assert.equal(result.status,'WARNING');assert.equal(result.differences.length,1);assert.equal(result.differences[0].severity,'WARNING')})

test('missing and extra accounts fail certification',()=>{const qb=snapshot([{key:'cash',label:'Cash',values:{ending_balance:100}}]);const hisab=snapshot([{key:'bank',label:'Bank',values:{ending_balance:100}}]);const result=compareSnapshots({quickBooks:qb,hisab});assert.equal(result.status,'FAILED');assert.equal(result.differences.length,2)})

test('cross-report controls detect unbalanced ledger and subledger differences',()=>{const values=new Map<string,FinancialReportSnapshot>();values.set('trial-balance',snapshot([{key:'ar',label:'Accounts Receivable',values:{debit:110,credit:10,ending_balance:100}},{key:'ap',label:'Accounts Payable',values:{debit:0,credit:90,ending_balance:90}}]));values.set('aged-ar',snapshot([{key:'customer',label:'Customer',values:{ending_balance:95}}],'aged-ar'));values.set('aged-ap',snapshot([{key:'vendor',label:'Vendor',values:{ending_balance:90}}],'aged-ap'));const result=validateCrossReportIntegrity(values,parameters);assert.equal(result.status,'FAILED');assert.ok(result.differences.some(item=>item.key==='debits-credits'));assert.ok(result.differences.some(item=>item.key==='ar-control'))})

test('comparison remains deterministic for a large report',()=>{const rows=Array.from({length:100000},(_,index)=>({key:`account-${index}`,label:`Account ${index}`,values:{debit:index,credit:index}}));const result=compareSnapshots({quickBooks:snapshot(rows),hisab:snapshot([...rows].reverse())});assert.equal(result.status,'MATCHED');assert.equal(result.matchedRows,100000)})

test('multi-currency reports cannot match when report currencies differ',()=>{const qb=snapshot([{key:'cash',label:'Cash',values:{ending_balance:100}}]);const hisab={...snapshot([{key:'cash',label:'Cash',values:{ending_balance:100}}]),currency:'SAR'};const result=compareSnapshots({quickBooks:qb,hisab});assert.equal(result.status,'FAILED');assert.ok(result.differences.some(item=>item.key==='report-currency'))})

test('inventory certification separates quantity and value differences',()=>{const qb=snapshot([{key:'widget',label:'Widget',values:{quantity:10,value:250}}],'inventory-valuation');const hisab=snapshot([{key:'widget',label:'Widget',values:{quantity:9,value:225}}],'inventory-valuation');const result=compareSnapshots({quickBooks:qb,hisab});assert.equal(result.status,'FAILED');assert.deepEqual(result.differences.map(item=>item.metric).sort(),['quantity','value'])})
