import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'
import { compareFxRows,parseQuickBooksFxGeneralLedger } from '../../src/lib/quickbooks-certification/multicurrency-engine'
import type { CertificationParameters } from '../../src/lib/quickbooks-certification/types'

const parameters:CertificationParameters={startDate:'2025-01-01',endDate:'2026-12-31',asOfDate:'2026-12-31',accountingBasis:'Accrual',homeCurrency:'USD',multiCurrency:true,exact:true,absoluteTolerance:0,relativeTolerance:0}
const payload={Header:{Currency:'USD'},Columns:{Column:[{ColTitle:'Date'},{ColTitle:'Transaction Type'},{ColTitle:'Num'},{ColTitle:'Memo/Description'},{ColTitle:'Account'},{ColTitle:'Currency'},{ColTitle:'Exchange Rate'},{ColTitle:'Foreign Amount'},{ColTitle:'Amount'}]},Rows:{Row:[{ColData:[{value:'2025-01-15'},{value:'Invoice'},{value:'INV-1'},{value:'Sale'},{value:'Accounts Receivable'},{value:'EUR'},{value:'1.1'},{value:'100.00'},{value:'110.00'}]},{ColData:[{value:'2026-12-31'},{value:'Journal Entry'},{value:'HCA-1'},{value:'Home currency revaluation'},{value:'Unrealized FX Gain'},{value:'USD'},{value:'1'},{value:'25'},{value:'25'}]}]}}

test('QuickBooks FX ledger parser retains transaction and home-currency evidence',()=>{const result=parseQuickBooksFxGeneralLedger(payload,'USD');assert.equal(result.reportCurrency,'USD');assert.equal(result.rows[0].currency,'EUR');assert.equal(result.rows[0].foreignAmount,100);assert.equal(result.rows[0].homeAmount,110);assert.equal(result.rows[0].exchangeRate,1.1);assert.equal(result.missingForeignEvidence,0)})

test('revaluation and currency gain/loss rows are classified separately',()=>{const result=parseQuickBooksFxGeneralLedger(payload,'USD');assert.equal(result.rows[1].classification,'UNREALIZED');assert.equal(result.rows[1].isFxAccount,true)})

test('every currency and historical rate can certify independently',()=>{const source=[{key:'eur:2025-01-15',label:'EUR',currency:'EUR',values:{rate:1.1,balance:100}},{key:'gbp:2025-06-20',label:'GBP',currency:'GBP',values:{rate:1.25,balance:80}}],hisab=source.map(row=>({...row,values:{...row.values}}));const result=compareFxRows('fx-exchange-rates','Historical rates',source,hisab,parameters);assert.equal(result.status,'MATCHED');assert.equal(result.matchedRows,2)})

test('a historical rate mismatch fails with transaction drill-down',()=>{const result=compareFxRows('fx-transactions','FX transactions',[{key:'Invoice:42:EUR',label:'Invoice 42',currency:'EUR',sourceId:'42',values:{transactionAmount:100,homeAmount:110,exchangeRate:1.1}}],[{key:'Invoice:42:EUR',label:'Invoice 42',currency:'EUR',localId:'local-42',values:{transactionAmount:100,homeAmount:109,exchangeRate:1.09}}],parameters);assert.equal(result.status,'FAILED');assert.deepEqual(result.differences.map(item=>item.metric).sort(),['exchangeRate','homeAmount']);assert.equal(result.differences[0].sourceRefs?.[0].sourceId,'42');assert.equal(result.differences[0].sourceRefs?.[0].documentId,'local-42')})

test('missing foreign amounts cannot be treated as home-currency evidence',()=>{const missing={...payload,Rows:{Row:[{ColData:[{value:'2025-01-15'},{value:'Invoice'},{value:'INV-1'},{value:'Sale'},{value:'Accounts Receivable'},{value:'EUR'},{value:'1.1'},{value:''},{value:'110.00'}]}]}};assert.equal(parseQuickBooksFxGeneralLedger(missing,'USD').missingForeignEvidence,1)})

test('realized and unrealized FX are certified independently per currency',()=>{const source=[{key:'realized:EUR',label:'Realized EUR',currency:'EUR',values:{homeAmount:12}},{key:'unrealized:GBP',label:'Unrealized GBP',currency:'GBP',values:{homeAmount:-7}}];const realized=compareFxRows('fx-realized','Realized FX',[source[0]],[{...source[0],values:{homeAmount:12}}],parameters),unrealized=compareFxRows('fx-unrealized','Unrealized FX',[source[1]],[{...source[1],values:{homeAmount:-6}}],parameters);assert.equal(realized.status,'MATCHED');assert.equal(unrealized.status,'FAILED');assert.equal(unrealized.differences[0].label,'Unrealized GBP')})

test('revaluation journal mismatch fails with source and local references',()=>{const result=compareFxRows('fx-revaluations','Revaluations',[{key:'2026-12-31:EUR',label:'EUR revaluation',currency:'EUR',sourceId:'qb-hca-1',values:{adjustment:25}}],[{key:'2026-12-31:EUR',label:'EUR revaluation',currency:'EUR',localId:'hisab-rv-1',values:{adjustment:24.5}}],parameters);assert.equal(result.status,'FAILED');assert.equal(result.differences[0].metric,'adjustment');assert.deepEqual(result.differences[0].sourceRefs,[{sourceId:'qb-hca-1',documentId:'hisab-rv-1'}])})

test('migration preserves QuickBooks overrides and realized FX posts separately',()=>{const adapter=readFileSync('src/lib/import-export/sources/quickbooks.adapter.ts','utf8'),transactions=readFileSync('src/lib/import-export/registry/modules/transactions.module.ts','utf8'),posting=readFileSync('src/lib/accounting/document-posting.ts','utf8');assert.match(adapter,/homeTotal: value\(row\.HomeTotalAmt/);assert.match(transactions,/source:'QUICKBOOKS_TRANSACTION'/);assert.match(transactions,/base_total:r\.homeTotal/);assert.match(posting,/sourceType:'REALIZED_FX'/);assert.match(posting,/currency:roles\.baseCurrency/)})

test('database aggregation is partition-safe and detects invalid rates',()=>{const sql=readFileSync('supabase/migrations/055_quickbooks_multicurrency_certification.sql','utf8');assert.match(sql,/certification_fx_ledger_by_source/);assert.match(sql,/invalid_rate_count/);assert.match(sql,/certification_fx_account_balances/);assert.match(sql,/entry\.entry_date>=p_from AND entry\.entry_date<=p_to/)})
