'use client'

import { useCallback, useEffect, useState } from 'react'
import { PageHeader } from '@/components/ui/page-header'
import { Button } from '@/components/ui/button'
import { Input, Select, Textarea } from '@/components/ui/input'
import { readApiError } from '@/lib/api-client'

type Option = { id: string; name: string; accountType?: string; account_type?: string; code?: string }
type Tab = 'refunds' | 'time' | 'billable' | 'cards' | 'tax' | 'masters' | 'reports'
const today = () => new Date().toISOString().slice(0, 10)

async function json(url: string) { const response = await fetch(url); if (!response.ok) throw new Error(await readApiError(response)); return response.json() }
async function send(url: string, method: string, body: unknown) { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (!response.ok) throw new Error(await readApiError(response)); return response.json() }

export default function AccountingOperationsPage() {
  const [tab, setTab] = useState<Tab>('refunds')
  const [busy, setBusy] = useState(false)
  const [message, setMessage] = useState('')
  const [customers, setCustomers] = useState<Option[]>([]), [employees, setEmployees] = useState<Option[]>([]), [vendors, setVendors] = useState<Option[]>([])
  const [projects, setProjects] = useState<Option[]>([]), [banks, setBanks] = useState<Option[]>([]), [accounts, setAccounts] = useState<Option[]>([])
  const [methods, setMethods] = useState<Option[]>([]), [types, setTypes] = useState<Option[]>([]), [agencies, setAgencies] = useState<Option[]>([])
  const [payrollEntries, setPayrollEntries] = useState<Option[]>([])
  const [refunds, setRefunds] = useState<Record<string, unknown>[]>([]), [times, setTimes] = useState<Record<string, unknown>[]>([])
  const [cards, setCards] = useState<Record<string, unknown>[]>([]), [charges, setCharges] = useState<{ timeActivities: Record<string, unknown>[]; expenses: Record<string, unknown>[] }>({ timeActivities: [], expenses: [] })
  const [taxData, setTaxData] = useState<{ periods: Record<string, unknown>[]; settlements: Record<string, unknown>[] }>({ periods: [], settlements: [] })
  const [reports, setReports] = useState<Record<string, unknown>>({})
  const [refund, setRefund] = useState({ customerId: '', bankAccountId: '', paymentMethodId: '', date: today(), reason: '', description: '', quantity: 1, unitPrice: 0, taxRate: 0, accountId: '' })
  const [refundVoid, setRefundVoid] = useState({ id: '', date: today(), reason: '' })
  const [time, setTime] = useState({ workerType: 'employee', workerId: '', customerId: '', projectId: '', payrollEntryId: '', date: today(), description: '', hours: 1, costRate: 0, billingRate: 0, isBillable: true })
  const [billable, setBillable] = useState({ customerId: '', timeActivityIds: '', expenseIds: '', date: today(), dueDate: today(), taxRate: 0 })
  const [expenseCharge, setExpenseCharge] = useState({ expenseId: '', customerId: '', projectId: '', markupPercent: 0 })
  const [card, setCard] = useState({ bankAccountId: '', creditCardAccountId: '', paymentMethodId: '', date: today(), amount: 0, feeAmount: 0, feeAccountId: '', reference: '' })
  const [cardReconcileId, setCardReconcileId] = useState('')
  const [filing, setFiling] = useState({ taxAgencyId: '', periodStart: today(), periodEnd: today(), dueDate: today() })
  const [settlement, setSettlement] = useState({ action: 'settle', type: 'PAYMENT', taxAgencyId: '', filingPeriodId: '', bankAccountId: '', date: today(), amount: 0, reference: '' })
  const [master, setMaster] = useState({ kind: 'customer-types', code: '', name: '', methodType: 'OTHER', liabilityAccountId: '', receivableAccountId: '' })
  const [assignment, setAssignment] = useState({ customerId: '', customerTypeId: '' })

  const load = useCallback(async () => {
    try {
      const results = await Promise.all([json('/api/customers'), json('/api/employees'), json('/api/vendors'), json('/api/cost-centers?type=PROJECT'), json('/api/banking/accounts?active=true'), json('/api/accounts'), json('/api/product-master/payment-methods'), json('/api/product-master/customer-types'), json('/api/product-master/tax-agencies'), json('/api/refund-receipts'), json('/api/time-activities'), json('/api/billable-charges'), json('/api/credit-card-payments'), json('/api/tax-filings'), json('/api/reports/product-parity'), json('/api/payroll')])
      setCustomers(results[0]); setEmployees(results[1]); setVendors(results[2]); setProjects(results[3]); setBanks(results[4]); setAccounts(results[5]); setMethods(results[6]); setTypes(results[7]); setAgencies(results[8]); setRefunds(results[9]); setTimes(results[10]); setCharges(results[11]); setCards(results[12]); setTaxData(results[13]); setReports(results[14])
      setPayrollEntries((results[15] ?? []).filter((entry: Record<string, unknown>) => ['DRAFT','PENDING'].includes(String(entry.status))).map((entry: Record<string, unknown>) => ({ id: String(entry.id), name: String(entry.payrollNo ?? entry.payroll_no ?? entry.period ?? entry.id) })))
    } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) }
  }, [])
  useEffect(() => { const timer = window.setTimeout(() => { void load() }, 0); return () => window.clearTimeout(timer) }, [load])
  async function act(work: () => Promise<unknown>) { setBusy(true); setMessage(''); try { await work(); setMessage('Saved successfully.'); await load() } catch (error) { setMessage(error instanceof Error ? error.message : String(error)) } finally { setBusy(false) } }
  const cardAccounts = banks.filter(bank => (bank.accountType ?? bank.account_type) === 'CREDIT_CARD')
  const bankAccounts = banks.filter(bank => (bank.accountType ?? bank.account_type) !== 'CREDIT_CARD')
  const tabs: Array<[Tab, string]> = [['refunds','Refund Receipts'],['time','Time Activities'],['billable','Billable Charges'],['cards','Card Pay Down'],['tax','Tax Agencies'],['masters','Masters'],['reports','Reports']]
  const options = (items: Option[]) => items.map(item => <option key={item.id} value={item.id}>{item.code ? `${item.code} · ` : ''}{item.name}</option>)

  return <div className="mx-auto max-w-[1600px] space-y-5 p-4 md:p-6">
    <PageHeader title="Accounting Operations" subtitle="Refunds, billable work, card payments, time, tax agencies, and reusable masters" breadcrumb={[{ label: 'Accounting' }, { label: 'Operations' }]} />
    <div className="flex flex-wrap gap-2">{tabs.map(([key,label]) => <button key={key} onClick={() => setTab(key)} className={`rounded-xl px-4 py-2 text-sm font-medium ${tab === key ? 'bg-indigo-600 text-white' : 'border bg-white text-slate-600'}`}>{label}</button>)}</div>
    {message && <div className={`rounded-xl border px-4 py-3 text-sm ${message === 'Saved successfully.' ? 'border-emerald-200 bg-emerald-50 text-emerald-700' : 'border-red-200 bg-red-50 text-red-700'}`}>{message}</div>}

    {tab === 'refunds' && <Panel title="Post Refund Receipt" note="Reverses revenue and tax, credits the bank, and returns linked inventory.">
      <Grid><Select label="Customer" value={refund.customerId} onChange={e=>setRefund({...refund,customerId:e.target.value})}><option value="">Select</option>{options(customers)}</Select><Select label="Bank account" value={refund.bankAccountId} onChange={e=>setRefund({...refund,bankAccountId:e.target.value})}><option value="">Select</option>{options(bankAccounts)}</Select><Select label="Payment method" value={refund.paymentMethodId} onChange={e=>setRefund({...refund,paymentMethodId:e.target.value})}><option value="">Select</option>{options(methods)}</Select><Input label="Date" type="date" value={refund.date} onChange={e=>setRefund({...refund,date:e.target.value})}/><Select label="Revenue account" value={refund.accountId} onChange={e=>setRefund({...refund,accountId:e.target.value})}><option value="">Default income account</option>{options(accounts)}</Select><Input label="Description" value={refund.description} onChange={e=>setRefund({...refund,description:e.target.value})}/><Input label="Quantity" type="number" value={refund.quantity} onChange={e=>setRefund({...refund,quantity:Number(e.target.value)})}/><Input label="Unit price" type="number" value={refund.unitPrice} onChange={e=>setRefund({...refund,unitPrice:Number(e.target.value)})}/><Input label="Tax %" type="number" value={refund.taxRate} onChange={e=>setRefund({...refund,taxRate:Number(e.target.value)})}/></Grid><Textarea label="Reason" value={refund.reason} onChange={e=>setRefund({...refund,reason:e.target.value})}/><Button loading={busy} onClick={()=>act(()=>send('/api/refund-receipts','POST',{...refund,lines:[{description:refund.description,quantity:refund.quantity,unitPrice:refund.unitPrice,taxRate:refund.taxRate,accountId:refund.accountId||null}]}))}>Post refund</Button><h3 className="font-semibold">Void posted refund</h3><Grid><Input label="Refund ID" value={refundVoid.id} onChange={e=>setRefundVoid({...refundVoid,id:e.target.value})}/><Input label="Void date" type="date" value={refundVoid.date} onChange={e=>setRefundVoid({...refundVoid,date:e.target.value})}/><Input label="Reason" value={refundVoid.reason} onChange={e=>setRefundVoid({...refundVoid,reason:e.target.value})}/></Grid><Button variant="outline" loading={busy} onClick={()=>act(()=>send(`/api/refund-receipts/${refundVoid.id}`,'DELETE',refundVoid))}>Void with reversal</Button><Records rows={refunds} fields={['id','refund_no','date','total','status']}/>
    </Panel>}

    {tab === 'time' && <Panel title="Time Activity" note="Tracks employee or vendor cost, customer/project billing, and optional payroll linkage."><Grid><Select label="Worker type" value={time.workerType} onChange={e=>setTime({...time,workerType:e.target.value,workerId:'',payrollEntryId:''})}><option value="employee">Employee</option><option value="vendor">Vendor</option></Select><Select label="Worker" value={time.workerId} onChange={e=>setTime({...time,workerId:e.target.value})}><option value="">Select</option>{options(time.workerType==='employee'?employees:vendors)}</Select><Select label="Customer" value={time.customerId} onChange={e=>setTime({...time,customerId:e.target.value})}><option value="">None</option>{options(customers)}</Select><Select label="Project" value={time.projectId} onChange={e=>setTime({...time,projectId:e.target.value})}><option value="">None</option>{options(projects)}</Select>{time.workerType==='employee'&&<Select label="Payroll entry" value={time.payrollEntryId} onChange={e=>setTime({...time,payrollEntryId:e.target.value})}><option value="">Do not add to payroll</option>{options(payrollEntries)}</Select>}<Input label="Date" type="date" value={time.date} onChange={e=>setTime({...time,date:e.target.value})}/><Input label="Hours" type="number" value={time.hours} onChange={e=>setTime({...time,hours:Number(e.target.value)})}/><Input label="Cost rate" type="number" value={time.costRate} onChange={e=>setTime({...time,costRate:Number(e.target.value)})}/><Input label="Billing rate" type="number" value={time.billingRate} onChange={e=>setTime({...time,billingRate:Number(e.target.value)})}/></Grid><Textarea label="Description" value={time.description} onChange={e=>setTime({...time,description:e.target.value})}/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={time.isBillable} onChange={e=>setTime({...time,isBillable:e.target.checked})}/>Billable</label><Button loading={busy} onClick={()=>act(()=>send('/api/time-activities','POST',{...time,employeeId:time.workerType==='employee'?time.workerId:null,vendorId:time.workerType==='vendor'?time.workerId:null,payrollEntryId:time.payrollEntryId||null}))}>Save activity</Button><Records rows={times} fields={['activity_no','activity_date','hours','status']}/></Panel>}

    {tab === 'billable' && <Panel title="Convert Billable Charges" note="Mark approved expenses billable, then combine eligible time and expenses into an invoice with stored cost and margin links."><h3 className="font-semibold">Mark expense billable</h3><Grid><Input label="Expense ID" value={expenseCharge.expenseId} onChange={e=>setExpenseCharge({...expenseCharge,expenseId:e.target.value})}/><Select label="Customer" value={expenseCharge.customerId} onChange={e=>setExpenseCharge({...expenseCharge,customerId:e.target.value})}><option value="">Select</option>{options(customers)}</Select><Select label="Project" value={expenseCharge.projectId} onChange={e=>setExpenseCharge({...expenseCharge,projectId:e.target.value})}><option value="">None</option>{options(projects)}</Select><Input label="Markup %" type="number" value={expenseCharge.markupPercent} onChange={e=>setExpenseCharge({...expenseCharge,markupPercent:Number(e.target.value)})}/></Grid><Button variant="outline" loading={busy} onClick={()=>act(()=>send('/api/billable-charges','PATCH',expenseCharge))}>Mark billable</Button><h3 className="font-semibold">Create customer invoice</h3><Grid><Select label="Customer" value={billable.customerId} onChange={e=>setBillable({...billable,customerId:e.target.value})}><option value="">Select</option>{options(customers)}</Select><Input label="Time activity IDs" value={billable.timeActivityIds} onChange={e=>setBillable({...billable,timeActivityIds:e.target.value})}/><Input label="Expense IDs" value={billable.expenseIds} onChange={e=>setBillable({...billable,expenseIds:e.target.value})}/><Input label="Invoice date" type="date" value={billable.date} onChange={e=>setBillable({...billable,date:e.target.value})}/><Input label="Due date" type="date" value={billable.dueDate} onChange={e=>setBillable({...billable,dueDate:e.target.value})}/><Input label="Tax %" type="number" value={billable.taxRate} onChange={e=>setBillable({...billable,taxRate:Number(e.target.value)})}/></Grid><Button loading={busy} onClick={()=>act(()=>send('/api/billable-charges','POST',{...billable,timeActivityIds:billable.timeActivityIds.split(',').map(x=>x.trim()).filter(Boolean),expenseIds:billable.expenseIds.split(',').map(x=>x.trim()).filter(Boolean)}))}>Create invoice</Button><h3 className="font-semibold">Unbilled time</h3><Records rows={charges.timeActivities} fields={['id','activity_no','description','hours','billing_rate']}/><h3 className="font-semibold">Unbilled expenses</h3><Records rows={charges.expenses} fields={['id','expense_no','total','markup_percent']}/></Panel>}

    {tab === 'cards' && <Panel title="Credit Card Pay Down" note="Transfers bank funds to the card liability, records fees, and creates matched reconciliation entries."><Grid><Select label="Bank" value={card.bankAccountId} onChange={e=>setCard({...card,bankAccountId:e.target.value})}><option value="">Select</option>{options(bankAccounts)}</Select><Select label="Credit card" value={card.creditCardAccountId} onChange={e=>setCard({...card,creditCardAccountId:e.target.value})}><option value="">Select</option>{options(cardAccounts)}</Select><Select label="Payment method" value={card.paymentMethodId} onChange={e=>setCard({...card,paymentMethodId:e.target.value})}><option value="">Select</option>{options(methods)}</Select><Input label="Date" type="date" value={card.date} onChange={e=>setCard({...card,date:e.target.value})}/><Input label="Amount" type="number" value={card.amount} onChange={e=>setCard({...card,amount:Number(e.target.value)})}/><Input label="Fee" type="number" value={card.feeAmount} onChange={e=>setCard({...card,feeAmount:Number(e.target.value)})}/><Select label="Fee account" value={card.feeAccountId} onChange={e=>setCard({...card,feeAccountId:e.target.value})}><option value="">None</option>{options(accounts)}</Select><Input label="Reference" value={card.reference} onChange={e=>setCard({...card,reference:e.target.value})}/></Grid><Button loading={busy} onClick={()=>act(()=>send('/api/credit-card-payments','POST',card))}>Post payment</Button><h3 className="font-semibold">Reconcile pay down</h3><div className="flex max-w-xl gap-3"><Input label="Payment ID" value={cardReconcileId} onChange={e=>setCardReconcileId(e.target.value)}/><Button variant="outline" loading={busy} onClick={()=>act(()=>send('/api/credit-card-payments','PATCH',{id:cardReconcileId}))}>Reconcile</Button></div><Records rows={cards} fields={['id','payment_no','date','amount','fee_amount','reconciliation_status']}/></Panel>}

    {tab === 'tax' && <Panel title="Tax Filing and Settlement" note="Filing periods calculate the agency control-account activity; payments and refunds post to the ledger and bank reconciliation."><Grid><Select label="Agency" value={filing.taxAgencyId} onChange={e=>setFiling({...filing,taxAgencyId:e.target.value})}><option value="">Select</option>{options(agencies)}</Select><Input label="Period start" type="date" value={filing.periodStart} onChange={e=>setFiling({...filing,periodStart:e.target.value})}/><Input label="Period end" type="date" value={filing.periodEnd} onChange={e=>setFiling({...filing,periodEnd:e.target.value})}/><Input label="Due date" type="date" value={filing.dueDate} onChange={e=>setFiling({...filing,dueDate:e.target.value})}/></Grid><Button loading={busy} onClick={()=>act(()=>send('/api/tax-filings','POST',filing))}>Create filing</Button><Grid><Select label="Type" value={settlement.type} onChange={e=>setSettlement({...settlement,type:e.target.value})}><option value="PAYMENT">Payment</option><option value="REFUND">Refund</option></Select><Select label="Agency" value={settlement.taxAgencyId} onChange={e=>setSettlement({...settlement,taxAgencyId:e.target.value})}><option value="">Select</option>{options(agencies)}</Select><Select label="Bank" value={settlement.bankAccountId} onChange={e=>setSettlement({...settlement,bankAccountId:e.target.value})}><option value="">Select</option>{options(bankAccounts)}</Select><Input label="Date" type="date" value={settlement.date} onChange={e=>setSettlement({...settlement,date:e.target.value})}/><Input label="Amount" type="number" value={settlement.amount} onChange={e=>setSettlement({...settlement,amount:Number(e.target.value)})}/><Input label="Reference" value={settlement.reference} onChange={e=>setSettlement({...settlement,reference:e.target.value})}/></Grid><Button loading={busy} onClick={()=>act(()=>send('/api/tax-filings','POST',settlement))}>Post settlement</Button><Records rows={taxData.periods} fields={['period_start','period_end','net_due','status']}/></Panel>}

    {tab === 'masters' && <Panel title="Reusable Masters" note="Customer types, payment methods, and tax agencies are company-scoped and permission-controlled."><Grid><Select label="Master" value={master.kind} onChange={e=>setMaster({...master,kind:e.target.value})}><option value="customer-types">Customer Type</option><option value="payment-methods">Payment Method</option><option value="tax-agencies">Tax Agency</option></Select><Input label="Code" value={master.code} onChange={e=>setMaster({...master,code:e.target.value})}/><Input label="Name" value={master.name} onChange={e=>setMaster({...master,name:e.target.value})}/>{master.kind==='payment-methods'&&<Select label="Method type" value={master.methodType} onChange={e=>setMaster({...master,methodType:e.target.value})}><option>CASH</option><option>BANK_TRANSFER</option><option>CARD</option><option>CHEQUE</option><option>OTHER</option></Select>}{master.kind==='tax-agencies'&&<><Select label="Liability account" value={master.liabilityAccountId} onChange={e=>setMaster({...master,liabilityAccountId:e.target.value})}><option value="">Select</option>{options(accounts)}</Select><Select label="Receivable account" value={master.receivableAccountId} onChange={e=>setMaster({...master,receivableAccountId:e.target.value})}><option value="">Optional</option>{options(accounts)}</Select></>}</Grid><Button loading={busy} onClick={()=>act(()=>send(`/api/product-master/${master.kind}`,'POST',master))}>Create master</Button><Grid><Select label="Customer" value={assignment.customerId} onChange={e=>setAssignment({...assignment,customerId:e.target.value})}><option value="">Select</option>{options(customers)}</Select><Select label="Customer type" value={assignment.customerTypeId} onChange={e=>setAssignment({...assignment,customerTypeId:e.target.value})}><option value="">None</option>{options(types)}</Select></Grid><Button variant="outline" loading={busy} onClick={()=>act(()=>send(`/api/customers/${assignment.customerId}/customer-type`,'PATCH',assignment))}>Assign type</Button></Panel>}

    {tab === 'reports' && <Panel title="Operational Accounting Reports" note="Refund, labor margin, credit-card fee, and tax filing summaries for the selected company."><pre className="overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify(reports,null,2)}</pre></Panel>}
  </div>
}

function Panel({ title, note, children }: { title: string; note: string; children: React.ReactNode }) { return <section className="space-y-4 rounded-2xl border bg-white p-5 shadow-sm"><div><h2 className="text-lg font-bold text-slate-800">{title}</h2><p className="text-sm text-slate-500">{note}</p></div>{children}</section> }
function Grid({ children }: { children: React.ReactNode }) { return <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{children}</div> }
function Records({ rows, fields }: { rows: Record<string, unknown>[]; fields: string[] }) { if (!rows.length) return <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No records.</p>; return <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-slate-50"><tr>{fields.map(field=><th key={field} className="px-3 py-2 text-left text-xs uppercase text-slate-500">{field.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{rows.slice(0,25).map((row,index)=><tr key={String(row.id??index)} className="border-t">{fields.map(field=><td key={field} className="max-w-xs truncate px-3 py-2">{String(row[field]??'—')}</td>)}</tr>)}</tbody></table></div> }
