import type { ReportCatalogEntry } from './types'

const FINANCIAL: ReportCatalogEntry[] = [
  { key: 'trial-balance', title: 'Trial Balance', description: 'Debit and credit totals for all accounts', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['accountNo', 'canonicalType'], columnFields: ['accountNo', 'accountName', 'debit', 'credit', 'balance'], groupFields: ['canonicalType'] },
  { key: 'balance-sheet', title: 'Balance Sheet', description: 'Assets, liabilities, and equity snapshot', category: 'financial', supportsExport: true, supportsCompare: true, supportsDrillDown: true, filterFields: [], columnFields: ['accountNo', 'name', 'balance'], groupFields: ['section'] },
  { key: 'profit-loss', title: 'Profit & Loss', description: 'Income statement for a period', category: 'financial', supportsExport: true, supportsCompare: true, supportsDrillDown: true, filterFields: [], columnFields: ['name', 'amount'], groupFields: ['canonicalType'] },
  { key: 'cash-flow', title: 'Cash Flow', description: 'Operating, investing, and financing cash flows', category: 'financial', supportsExport: true, supportsCompare: true, supportsDrillDown: false, filterFields: [], columnFields: ['month', 'inflows', 'outflows', 'net'], groupFields: ['month'] },
  { key: 'general-ledger', title: 'General Ledger', description: 'Account transaction detail', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['accountId', 'sourceType'], columnFields: ['date', 'description', 'debit', 'credit', 'balance'], groupFields: ['accountNo'] },
  { key: 'aged-ar', title: 'Aged Receivables', description: 'Outstanding receivables by aging bucket', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['bucket', 'customerName'], columnFields: ['invoiceNo', 'customerName', 'dueDate', 'balance', 'bucket'], groupFields: ['bucket', 'customerName'] },
  { key: 'aged-ap', title: 'Aged Payables', description: 'Outstanding payables by aging bucket', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['bucket', 'vendorName'], columnFields: ['billNo', 'vendorName', 'dueDate', 'balance', 'bucket'], groupFields: ['bucket', 'vendorName'] },
  { key: 'comparative-profit-loss', title: 'Comparative P&L', description: 'Period-over-period profit and loss', category: 'financial', supportsExport: true, supportsCompare: true, supportsDrillDown: false, filterFields: [], columnFields: ['metric', 'current', 'prior', 'variance'], groupFields: [] },
  { key: 'comparative-balance-sheet', title: 'Comparative Balance Sheet', description: 'Point-in-time balance sheet comparison', category: 'financial', supportsExport: true, supportsCompare: true, supportsDrillDown: false, filterFields: [], columnFields: ['section', 'current', 'prior'], groupFields: [] },
  { key: 'retained-earnings', title: 'Retained Earnings', description: 'Retained earnings roll-forward', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['line', 'amount'], groupFields: [] },
  { key: 'equity-statement', title: 'Equity Statement', description: 'Statement of changes in equity', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['accountNo', 'name', 'balance'], groupFields: [] },
  { key: 'financial-ratios', title: 'Financial Ratios', description: 'Liquidity, leverage, and margin ratios', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['ratio', 'value'], groupFields: [] },
  { key: 'budget-vs-actual', title: 'Budget vs Actual', description: 'Budget variance by account', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['canonicalType'], columnFields: ['accountName', 'budget', 'actual', 'variance', 'variancePct'], groupFields: ['canonicalType'] },
  { key: 'journal-report', title: 'Journal Report', description: 'Journal entries for a period', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['status'], columnFields: ['entryNo', 'date', 'description', 'totalDebit', 'totalCredit', 'status'], groupFields: ['status'] },
  { key: 'customer-ledger', title: 'Customer Ledger', description: 'Customer invoice activity', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['customerId'], columnFields: ['invoiceNo', 'date', 'customerName', 'total', 'balance'], groupFields: ['customerName'] },
  { key: 'vendor-ledger', title: 'Vendor Ledger', description: 'Vendor bill activity', category: 'financial', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['vendorId'], columnFields: ['billNo', 'date', 'vendorName', 'total', 'balance'], groupFields: ['vendorName'] },
]

const OPERATIONAL: ReportCatalogEntry[] = [
  { key: 'sales-summary', title: 'Sales Summary', description: 'Invoice sales for a period', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['customerName', 'status'], columnFields: ['invoiceNo', 'date', 'customerName', 'total', 'balance'], groupFields: ['customerName'] },
  { key: 'purchase-summary', title: 'Purchase Summary', description: 'Vendor bills for a period', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['vendorName', 'status'], columnFields: ['billNo', 'date', 'vendorName', 'total', 'balance'], groupFields: ['vendorName'] },
  { key: 'expense-summary', title: 'Expense Summary', description: 'Expense claims and payments', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['category'], columnFields: ['expenseNo', 'date', 'category', 'total'], groupFields: ['category'] },
  { key: 'inventory-valuation', title: 'Inventory Valuation', description: 'Stock value by warehouse', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['warehouse'], columnFields: ['itemName', 'quantity', 'unitCost', 'totalValue'], groupFields: ['warehouse'] },
  { key: 'inventory-movement', title: 'Inventory Movement', description: 'Stock movements for a period', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['movement_type'], columnFields: ['date', 'type', 'itemName', 'quantity', 'totalCost'], groupFields: ['type'] },
  { key: 'payroll-summary', title: 'Payroll Summary', description: 'Payroll runs for a period', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['status'], columnFields: ['payrollNo', 'employeeName', 'netSalary'], groupFields: ['employeeName'] },
  { key: 'tax-report', title: 'Tax Report', description: 'VAT collected and paid', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['line', 'amount'], groupFields: [] },
  { key: 'bank-summary', title: 'Bank Summary', description: 'Bank account cash movements', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['accountNo'], columnFields: ['accountName', 'inflows', 'outflows', 'net'], groupFields: [] },
  { key: 'customer-aging', title: 'Customer Aging', description: 'Alias for aged receivables', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['bucket'], columnFields: ['invoiceNo', 'customerName', 'balance', 'bucket'], groupFields: ['bucket'] },
  { key: 'vendor-aging', title: 'Vendor Aging', description: 'Alias for aged payables', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['bucket'], columnFields: ['billNo', 'vendorName', 'balance', 'bucket'], groupFields: ['bucket'] },
  { key: 'top-customers', title: 'Top Customers', description: 'Highest revenue customers', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['rank', 'customerName', 'total', 'invoiceCount'], groupFields: [] },
  { key: 'top-vendors', title: 'Top Vendors', description: 'Highest spend vendors', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['rank', 'vendorName', 'total', 'billCount'], groupFields: [] },
  { key: 'top-products', title: 'Top Products', description: 'Best-selling line items', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['rank', 'product', 'total', 'quantity'], groupFields: [] },
  { key: 'cost-center-report', title: 'Cost Center Report', description: 'Ledger activity by cost center', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: ['costCenter'], columnFields: ['costCenter', 'debit', 'credit', 'net'], groupFields: ['costCenter'] },
  { key: 'department-profitability', title: 'Department Profitability', description: 'Payroll cost by department', category: 'operational', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: ['department'], columnFields: ['department', 'payrollCost'], groupFields: ['department'] },
]

const ANALYTICS: ReportCatalogEntry[] = [
  { key: 'executive-dashboard', title: 'Executive Dashboard', description: 'Financial KPIs overview', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: [], groupFields: [] },
  { key: 'revenue-trends', title: 'Revenue Trends', description: 'Monthly revenue trend', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['month', 'revenue', 'netProfit'], groupFields: ['month'] },
  { key: 'expense-trends', title: 'Expense Trends', description: 'Monthly expense trend', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['month', 'expenses', 'cogs'], groupFields: ['month'] },
  { key: 'cash-position', title: 'Cash Position', description: 'Cash inflows and outflows', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['month', 'inflows', 'outflows', 'net'], groupFields: [] },
  { key: 'working-capital', title: 'Working Capital', description: 'Current assets minus liabilities', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['metric', 'amount'], groupFields: [] },
  { key: 'profit-margins', title: 'Profit Margins', description: 'Gross and net margin analysis', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['margin', 'value'], groupFields: [] },
  { key: 'receivable-turnover', title: 'Receivable Turnover', description: 'AR turnover and DSO', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['metric', 'value'], groupFields: [] },
  { key: 'payable-turnover', title: 'Payable Turnover', description: 'AP turnover and DPO', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['metric', 'value'], groupFields: [] },
  { key: 'inventory-turnover', title: 'Inventory Turnover', description: 'COGS-based inventory turnover', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: false, filterFields: [], columnFields: ['metric', 'value'], groupFields: [] },
  { key: 'budget-variance', title: 'Budget Variance Analysis', description: 'Budget vs actual variance', category: 'analytics', supportsExport: true, supportsCompare: false, supportsDrillDown: true, filterFields: [], columnFields: ['accountName', 'budget', 'actual', 'variance'], groupFields: [] },
]

export const REPORT_CATALOG: ReportCatalogEntry[] = [...FINANCIAL, ...OPERATIONAL, ...ANALYTICS]

export function getReportCatalogEntry(key: string): ReportCatalogEntry | undefined {
  return REPORT_CATALOG.find((r) => r.key === key)
}

export function listReportCatalog(category?: string): ReportCatalogEntry[] {
  if (!category) return REPORT_CATALOG
  return REPORT_CATALOG.filter((r) => r.category === category)
}
