import type { CutoffBalance,CutoffDifference,CutoffSection } from './types'

const round=(value:number)=>Math.round(value*1000000)/1000000
export function openingAsOfDate(mode:'FULL_HISTORY'|'OPENING_BALANCE_ONLY'|'HYBRID',cutoffDate:string,reconciliationDate:string){if(mode==='OPENING_BALANCE_ONLY')return reconciliationDate;if(mode==='FULL_HISTORY')return cutoffDate;const date=new Date(`${cutoffDate}T00:00:00Z`);date.setUTCDate(date.getUTCDate()-1);return date.toISOString().slice(0,10)}
export function reconcileCutoffBalances(key:string,label:string,balances:CutoffBalance[],tolerance:number,exact=false):CutoffSection{
  const differences:CutoffDifference[]=[];let matched=0;let maximumDifference=0;const allowed=exact?0:Math.max(0,tolerance)
  for(const balance of balances){const expectedClosing=round(balance.opening+balance.movement);const rollForwardDifference=round(expectedClosing-balance.quickBooksClosing);const closingDifference=round(balance.hisabClosing-balance.quickBooksClosing);maximumDifference=Math.max(maximumDifference,Math.abs(rollForwardDifference),Math.abs(closingDifference));if(Math.abs(rollForwardDifference)>allowed||Math.abs(closingDifference)>allowed)differences.push({...balance,expectedClosing,rollForwardDifference,closingDifference,severity:'ERROR',recommendedAction:Math.abs(rollForwardDifference)>allowed?'Reconcile the opening snapshot and post-cutoff transaction movement.':'Trace the Hisab closing balance to its opening journal and imported transactions.'});else if(Math.abs(rollForwardDifference)>0||Math.abs(closingDifference)>0)differences.push({...balance,expectedClosing,rollForwardDifference,closingDifference,severity:'WARNING',recommendedAction:'Review the immaterial rounding difference.'});else matched++}
  const errors=differences.filter(item=>item.severity==='ERROR').length;return {key,label,status:errors?'FAILED':differences.length?'WARNING':'MATCHED',matched,compared:balances.length,maximumDifference,differences}
}
