import 'server-only'
import { createHash,randomUUID } from 'node:crypto'
import { Provider } from '@/integrations/accounting/contracts/types'
import { createAccountingIntegrationRuntime } from '@/integrations/accounting/services/container'
import { materializeOpeningSubledgerBalances,postIdempotentOpeningBalance,type OpeningBalanceLine,type OpeningSubledgerBalance } from '@/lib/accounting/opening-balances'
import { processInventoryMovement } from '@/lib/inventory/movements'
import { createAdminClient } from '@/lib/supabase/admin'
import { compareSnapshots,normalizedKey } from '@/lib/quickbooks-certification/engine'
import { generateHisabSnapshot } from '@/lib/quickbooks-certification/hisab-reports'
import { buildQuickBooksReportRequest,normalizeQuickBooksReport } from '@/lib/quickbooks-certification/quickbooks-reports'
import type { CertificationParameters,CertificationReportKey,FinancialReportSnapshot } from '@/lib/quickbooks-certification/types'
import { openingAsOfDate,reconcileCutoffBalances } from './engine'
import type { CutoffBalance,CutoffConfiguration,CutoffReconciliationReport,CutoffSection,MigrationCutoffMode } from './types'

type Row=Record<string,unknown>
const datePattern=/^\d{4}-\d{2}-\d{2}$/
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value as Row).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:JSON.stringify(value)??'null'
const hash=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex')
const endOf=(date:string)=>`${date}T23:59:59.999Z`
const startOf=(date:string)=>`${date}T00:00:00.000Z`

export function validateCutoffConfiguration(input:Partial<CutoffConfiguration>):CutoffConfiguration{
  const today=new Date().toISOString().slice(0,10),mode:MigrationCutoffMode=['FULL_HISTORY','OPENING_BALANCE_ONLY','HYBRID'].includes(String(input.mode))?input.mode as MigrationCutoffMode:'HYBRID'
  const result:CutoffConfiguration={mode,cutoffDate:String(input.cutoffDate??today),reconciliationDate:String(input.reconciliationDate??today),accountingBasis:input.accountingBasis==='Cash'?'Cash':'Accrual',homeCurrency:input.homeCurrency?.trim().toUpperCase(),absoluteTolerance:Math.max(0,number(input.absoluteTolerance??0.01)),exact:Boolean(input.exact)}
  if(!datePattern.test(result.cutoffDate)||!datePattern.test(result.reconciliationDate))throw new Error('Cutoff and reconciliation dates must use YYYY-MM-DD.')
  if(result.cutoffDate>result.reconciliationDate)throw new Error('Cutoff date cannot be after reconciliation date.')
  if(result.accountingBasis==='Cash')throw new Error('Opening-balance certification requires accrual-basis source reports.')
  if(result.exact)result.absoluteTolerance=0
  return result
}

async function allRows(table:string,companyId:string,select:string){
  const db=createAdminClient(),output:Row[]=[];for(let from=0;;from+=1000){const result=await db.from(table).select(select).eq('company_id',companyId).range(from,from+999);if(result.error)throw result.error;output.push(...((result.data??[]) as unknown as Row[]));if((result.data?.length??0)<1000)break}return output
}
async function allQuickBooksAccounts(companyId:string,realmId:string){const db=createAdminClient(),output:Row[]=[];for(let from=0;;from+=1000){const result=await db.from('quickbooks_migration_records').select('realm_id,entity_type,source_id,currency_code,exchange_rate,source_payload').eq('company_id',companyId).eq('realm_id',realmId).eq('entity_type','Account').range(from,from+999);if(result.error)throw result.error;output.push(...((result.data??[]) as unknown as Row[]));if((result.data?.length??0)<1000)break}return output}
async function allOpeningLinks(companyId:string,realmId:string){const db=createAdminClient(),output:Row[]=[];for(let from=0;;from+=1000){const result=await db.from('quickbooks_migration_local_links').select('realm_id,entity_type,source_id,local_table,local_id').eq('company_id',companyId).eq('realm_id',realmId).in('entity_type',['Account','Customer','Vendor','Item']).range(from,from+999);if(result.error)throw result.error;output.push(...((result.data??[]) as unknown as Row[]));if((result.data?.length??0)<1000)break}return output}
function adapt(section:ReturnType<typeof compareSnapshots>):CutoffSection{return {key:section.reportKey,label:section.label,status:section.status==='UNAVAILABLE'?'FAILED':section.status,matched:section.matchedRows,compared:section.comparedRows,maximumDifference:section.maximumDifference,differences:section.differences.map(item=>({key:item.key,label:item.label,opening:0,movement:0,quickBooksClosing:item.quickBooksValue,hisabClosing:item.hisabValue,currency:'',expectedClosing:item.quickBooksValue,rollForwardDifference:0,closingDifference:item.difference,severity:item.severity,recommendedAction:item.recommendedAction,sourceId:item.sourceRefs?.[0]?.sourceId,localId:item.sourceRefs?.[0]?.documentId}))}}
function parameters(config:CutoffConfiguration,asOfDate:string,currency:string):CertificationParameters{return {startDate:config.mode==='FULL_HISTORY'?'1900-01-01':config.cutoffDate,endDate:config.reconciliationDate,asOfDate,accountingBasis:config.accountingBasis,homeCurrency:currency,multiCurrency:false,exact:config.exact,absoluteTolerance:config.absoluteTolerance,relativeTolerance:0}}
function balanceType(account:Row,currency:string,home:string){const text=normalizedKey(`${account.name??''} ${account.sub_type??''}`);if(currency!==home)return 'FOREIGN_CURRENCY';if(/bank|cash/.test(text))return 'BANK';if(/tax|vat/.test(text))return 'TAX';if(String(account.canonical_type)==='Equity')return 'EQUITY';return 'GENERAL_LEDGER'}

export async function runCutoffReconciliation(companyId:string,userId:string,input:Partial<CutoffConfiguration>):Promise<CutoffReconciliationReport>{
  const config=validateCutoffConfiguration(input),db=createAdminClient(),runtime=createAccountingIntegrationRuntime(),provider=runtime.providers.get(Provider.QUICKBOOKS),runId=randomUUID()
  if(!provider.getReports)throw new Error('The connected QuickBooks provider does not support accounting reports.')
  const connection=await runtime.connections.executeForProvider(companyId,Provider.QUICKBOOKS,async context=>({context,realmId:context.realmId,company:await provider.getCompanyInfo(context)}))
  const currency=String(connection.company.baseCurrency??config.homeCurrency??'SAR').toUpperCase();if(config.homeCurrency&&currency!==config.homeCurrency)throw new Error(`Cutoff currency must match the QuickBooks home currency (${currency}).`)
  const openingDate=openingAsOfDate(config.mode,config.cutoffDate,config.reconciliationDate)
  const existing=await db.from('quickbooks_cutoff_reconciliations').select('id,opening_journal_id,attempt_count').eq('company_id',companyId).eq('realm_id',connection.realmId).eq('mode',config.mode).eq('cutoff_date',config.cutoffDate).eq('reconciliation_date',config.reconciliationDate).maybeSingle();if(existing.error)throw existing.error
  const reconciliationId=existing.data?String(existing.data.id):runId
  const runData={id:reconciliationId,company_id:companyId,realm_id:connection.realmId,mode:config.mode,cutoff_date:config.cutoffDate,opening_as_of_date:openingDate,reconciliation_date:config.reconciliationDate,accounting_basis:config.accountingBasis,home_currency:currency,status:'GENERATING',created_by_id:userId,started_at:new Date().toISOString(),completed_at:null,last_error:null,attempt_count:Number(existing.data?.attempt_count??0)+1}
  const started=existing.data?await db.from('quickbooks_cutoff_reconciliations').update({...runData,id:undefined}).eq('id',reconciliationId).eq('company_id',companyId):await db.from('quickbooks_cutoff_reconciliations').insert(runData);if(started.error)throw started.error
  try{
    const reportKeys:CertificationReportKey[]=['trial-balance','balance-sheet','customer-balances','vendor-balances','inventory-valuation']
    const currentParams=parameters(config,config.reconciliationDate,currency),openingParams=parameters(config,openingDate,currency)
    const fetch=async(key:CertificationReportKey,p:CertificationParameters)=>{const request=buildQuickBooksReportRequest(key,p),response=await provider.getReports!(connection.context,[request]);return normalizeQuickBooksReport(key,response[request.reportName],p)}
    const currentEntries=await Promise.all(reportKeys.map(async key=>[key,await fetch(key,currentParams)] as const)),current=new Map(currentEntries)
    const opening=new Map<CertificationReportKey,FinancialReportSnapshot>()
    if(config.mode!=='FULL_HISTORY')for(const key of ['trial-balance','customer-balances','vendor-balances','inventory-valuation'] as CertificationReportKey[])opening.set(key,await fetch(key,openingParams))
    const [accounts,links,items,customers,vendors,sourceAccounts]=await Promise.all([allRows('chart_of_accounts',companyId,'id,account_no,name,full_name,canonical_type,normal_balance,sub_type'),allOpeningLinks(companyId,connection.realmId),allRows('inventory_items',companyId,'id,name,sku'),allRows('customers',companyId,'id,name,customer_no'),allRows('vendors',companyId,'id,name,vendor_no'),allQuickBooksAccounts(companyId,connection.realmId)])
    const accountById=new Map(accounts.map(row=>[String(row.id),row])),accountByName=new Map<string,Row>();for(const row of accounts)for(const name of [row.name,row.full_name,row.account_no])if(name)accountByName.set(normalizedKey(name),row)
    const linkMap=new Map(links.filter(row=>String(row.realm_id)===connection.realmId).map(row=>[`${row.entity_type}:${row.source_id}`,String(row.local_id)]))
    const sourceAccountMap=new Map(sourceAccounts.filter(row=>String(row.realm_id)===connection.realmId&&String(row.entity_type)==='Account').map(row=>[String(row.source_id),row]))
    const itemByName=new Map<string,Row>();for(const item of items)for(const name of [item.name,item.sku])if(name)itemByName.set(normalizedKey(name),item)
    const customerByName=new Map(customers.map(row=>[normalizedKey(row.name),row])),vendorByName=new Map(vendors.map(row=>[normalizedKey(row.name),row]))
    const details:Row[]=[],journalLines:OpeningBalanceLine[]=[],subledgerBalances:OpeningSubledgerBalance[]=[],openingByAccount=new Map<string,number>(),mappingErrors:CutoffBalance[]=[]
    for(const source of opening.get('trial-balance')?.rows??[]){
      const sourceId=source.sourceRefs?.[0]?.sourceId;const localId=(sourceId&&linkMap.get(`Account:${sourceId}`))??String(accountByName.get(source.key)?.id??'');const account=accountById.get(localId)
      const raw=number(source.values.ending_balance??((source.values.debit??0)-(source.values.credit??0)));if(Math.abs(raw)<0.000001)continue
      if(!account){mappingErrors.push({key:source.key,label:source.label,opening:raw,movement:0,quickBooksClosing:0,hisabClosing:0,currency,sourceId});continue}
      const archived=sourceId?sourceAccountMap.get(sourceId):undefined,payload=(archived?.source_payload&&typeof archived.source_payload==='object'?archived.source_payload:{}) as Row,currencyRef=(payload.CurrencyRef&&typeof payload.CurrencyRef==='object'?payload.CurrencyRef:{}) as Row,sourceCurrency=String(archived?.currency_code??currencyRef.value??currency).toUpperCase(),normal=String(account.normal_balance??'DEBIT'),signed=source.values.ending_balance!==undefined?raw:(normal==='CREDIT'?-raw:raw);openingByAccount.set(localId,signed)
      const debit=normal==='DEBIT'?(signed>=0?signed:0):(signed<0?Math.abs(signed):0),credit=normal==='CREDIT'?(signed>=0?signed:0):(signed<0?Math.abs(signed):0)
      journalLines.push({accountId:localId,debit,credit,description:`QuickBooks opening: ${source.label}`});details.push({reconciliation_id:reconciliationId,company_id:companyId,balance_type:balanceType(account,sourceCurrency,currency),source_key:source.key,source_name:source.label,source_id:sourceId??null,local_table:'chart_of_accounts',local_id:localId,account_id:localId,currency:sourceCurrency,debit,credit,value:signed,metadata:{normalBalance:normal,homeCurrency:currency,foreignAmount:sourceCurrency===currency?null:number(payload.CurrentBalanceWithSubAccounts??payload.CurrentBalance),exchangeRate:archived?.exchange_rate??null}})
    }
    for(const [reportKey,type,entity,table,names] of [['customer-balances','ACCOUNTS_RECEIVABLE','Customer','customers',customerByName],['vendor-balances','ACCOUNTS_PAYABLE','Vendor','vendors',vendorByName]] as const)for(const source of opening.get(reportKey)?.rows??[]){const sourceId=source.sourceRefs?.[0]?.sourceId,localId=(sourceId?linkMap.get(`${entity}:${sourceId}`):undefined)??String(names.get(source.key)?.id??''),amount=number(source.values.ending_balance);if(Math.abs(amount)>0.000001&&!localId)mappingErrors.push({key:`${type}:${source.key}`,label:source.label,opening:amount,movement:0,quickBooksClosing:amount,hisabClosing:0,currency,sourceId,category:type});if(localId&&Math.abs(amount)>0.000001)subledgerBalances.push({kind:type==='ACCOUNTS_RECEIVABLE'?'AR':'AP',sourceKey:source.key,partyId:localId,partyName:source.label,amount});details.push({reconciliation_id:reconciliationId,company_id:companyId,balance_type:type,source_key:source.key,source_name:source.label,source_id:sourceId??null,local_table:table,local_id:localId||null,currency,debit:type==='ACCOUNTS_RECEIVABLE'?amount:0,credit:type==='ACCOUNTS_PAYABLE'?amount:0,value:amount,metadata:{mapped:Boolean(localId),nativeDocument:true}})}
    for(const source of opening.get('inventory-valuation')?.rows??[]){const sourceId=source.sourceRefs?.[0]?.sourceId,localId=(sourceId&&linkMap.get(`Item:${sourceId}`))??String(itemByName.get(source.key)?.id??''),quantity=number(source.values.quantity),value=number(source.values.value);if((Math.abs(quantity)>0.000001||Math.abs(value)>0.000001)&&!localId)mappingErrors.push({key:`INVENTORY:${source.key}`,label:source.label,opening:value,movement:0,quickBooksClosing:value,hisabClosing:0,currency,sourceId,category:'INVENTORY'});details.push({reconciliation_id:reconciliationId,company_id:companyId,balance_type:'INVENTORY',source_key:source.key,source_name:source.label,source_id:sourceId??null,local_table:'inventory_items',local_id:localId||null,currency,quantity,value,metadata:{mapped:Boolean(localId)}})}
    const cleared=await db.from('quickbooks_opening_balance_details').delete().eq('reconciliation_id',reconciliationId);if(cleared.error)throw cleared.error
    if(details.length){const saved=await db.from('quickbooks_opening_balance_details').insert(details);if(saved.error)throw saved.error}
    let openingJournalId:string|null=existing.data?.opening_journal_id?String(existing.data.opening_journal_id):null
    if(config.mode!=='FULL_HISTORY'&&!mappingErrors.length){
      const posted=await postIdempotentOpeningBalance({companyId,userId,date:new Date(startOf(config.mode==='OPENING_BALANCE_ONLY'?config.reconciliationDate:config.cutoffDate)),currency,description:`QuickBooks ${config.mode.toLowerCase().replaceAll('_',' ')} opening balance`,idempotencyKey:`${connection.realmId}:${config.mode}:${config.cutoffDate}:${config.reconciliationDate}`,lines:journalLines});openingJournalId=posted.journalId
      await materializeOpeningSubledgerBalances({companyId,userId,reconciliationId,date:new Date(startOf(config.mode==='OPENING_BALANCE_ONLY'?config.reconciliationDate:config.cutoffDate)),currency,balances:subledgerBalances})
      for(const detail of details.filter(item=>item.balance_type==='INVENTORY'&&item.local_id&&Math.abs(number(item.quantity))>0)){const sourceId=`${reconciliationId}:${detail.source_key}`,unitCost=number(detail.value)/Math.abs(number(detail.quantity));const prior=await db.from('stock_movements').select('id,quantity,unit_cost').eq('company_id',companyId).eq('source_type','QUICKBOOKS_CUTOFF_OPENING').eq('source_id',sourceId).maybeSingle();if(prior.error)throw prior.error;if(prior.data&&(Math.abs(number(prior.data.quantity)-number(detail.quantity))>0.000001||Math.abs(number(prior.data.unit_cost)-unitCost)>0.000001))throw new Error(`QuickBooks opening inventory changed after posting for ${detail.source_name}. Reverse the prior movement before retrying.`);if(!prior.data)await processInventoryMovement({companyId,userId,inventoryItemId:String(detail.local_id),quantity:number(detail.quantity),unitCost,movementType:'ADJUSTMENT',sourceType:'QUICKBOOKS_CUTOFF_OPENING',sourceId,reference:`QuickBooks opening inventory: ${detail.source_name}`,movementDate:new Date(startOf(config.mode==='OPENING_BALANCE_ONLY'?config.reconciliationDate:config.cutoffDate)),postCogsJournal:false})}
    }
    const movementFrom=config.mode==='FULL_HISTORY'?'1900-01-01':config.cutoffDate
    const [movementResult,closingResult]=await Promise.all([db.rpc('aggregate_cutoff_ledger_movement',{p_company_id:companyId,p_from:startOf(movementFrom),p_to:endOf(config.reconciliationDate),p_excluded_opening_journal_id:openingJournalId}),db.rpc('aggregate_ledger_balances_for_report',{p_company_id:companyId,p_from:null,p_to:endOf(config.reconciliationDate)})]);if(movementResult.error)throw movementResult.error;if(closingResult.error)throw closingResult.error
    const movement=new Map<string,number>(((movementResult.data??[]) as unknown as Row[]).map(row=>[String(row.account_id),number(row.total_debit)-number(row.total_credit)])),hisabClosing=new Map<string,number>(((closingResult.data??[]) as unknown as Row[]).map(row=>[String(row.account_id),number(row.total_debit)-number(row.total_credit)])),qbClosing=new Map<string,number>()
    for(const source of current.get('trial-balance')!.rows){const sourceId=source.sourceRefs?.[0]?.sourceId,localId=(sourceId&&linkMap.get(`Account:${sourceId}`))??String(accountByName.get(source.key)?.id??''),account=accountById.get(localId),raw=number(source.values.ending_balance??((source.values.debit??0)-(source.values.credit??0)));if(!account){if(Math.abs(raw)>0.000001)mappingErrors.push({key:`CURRENT:${source.key}`,label:source.label,opening:0,movement:0,quickBooksClosing:raw,hisabClosing:0,currency,sourceId,category:'GENERAL_LEDGER'});continue}qbClosing.set(localId,source.values.ending_balance!==undefined?raw:(String(account.normal_balance)==='CREDIT'?-raw:raw))}
    const balances:CutoffBalance[]=[]
    for(const account of accounts){const id=String(account.id),normal=String(account.normal_balance??'DEBIT'),sign=normal==='CREDIT'?-1:1,key=normalizedKey(account.full_name??account.name),openingValue=config.mode==='FULL_HISTORY'?0:(openingByAccount.get(id)??0),movementValue=(movement.get(id)??0)*sign,currentValue=(hisabClosing.get(id)??0)*sign;balances.push({key,label:String(account.full_name??account.name),opening:openingValue,movement:config.mode==='OPENING_BALANCE_ONLY'?0:movementValue,quickBooksClosing:qbClosing.get(id)??0,hisabClosing:currentValue,currency,localId:id,category:balanceType(account,currency,currency)})}
    const sections:CutoffSection[]=[reconcileCutoffBalances('general-ledger','General Ledger roll-forward',balances,config.absoluteTolerance,config.exact)]
    sections.push({...sections[0],key:'trial-balance',label:'Trial Balance'})
    for(const key of ['balance-sheet','customer-balances','vendor-balances','inventory-valuation'] as CertificationReportKey[]){const hisab=await generateHisabSnapshot(companyId,key,currentParams)
      sections.push(adapt(compareSnapshots({quickBooks:current.get(key)!,hisab})))
    }
    if(mappingErrors.length)sections.push(reconcileCutoffBalances('relationships','Opening-balance relationships',mappingErrors,config.absoluteTolerance,config.exact))
    for(const section of sections)if(section.differences.some(item=>item.severity==='ERROR'))section.status='FAILED'
    const failed=sections.filter(section=>section.status==='FAILED').length,warnings=sections.filter(section=>section.status==='WARNING').length,status=failed?'FAILED':'PASSED'
    const report:CutoffReconciliationReport={id:reconciliationId,realmId:connection.realmId,mode:config.mode,cutoffDate:config.cutoffDate,openingAsOfDate:openingDate,reconciliationDate:config.reconciliationDate,accountingBasis:config.accountingBasis,homeCurrency:currency,openingJournalId,status,generatedAt:new Date().toISOString(),sections,summary:{matched:sections.filter(section=>section.status==='MATCHED').length,failed,warnings,differenceCount:sections.reduce((sum,section)=>sum+section.differences.length,0)}}
    const completed=await db.from('quickbooks_cutoff_reconciliations').update({status,source_hash:hash({opening:[...opening.values()],current:[...current.values()]}),opening_journal_id:openingJournalId,result:report,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',reconciliationId).eq('company_id',companyId);if(completed.error)throw completed.error
    return report
  }catch(error){await db.from('quickbooks_cutoff_reconciliations').update({status:'FAILED',last_error:error instanceof Error?error.message:String(error),completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',reconciliationId).eq('company_id',companyId);throw error}
}

export async function getCutoffReconciliations(companyId:string,id?:string){const db=createAdminClient();let query=db.from('quickbooks_cutoff_reconciliations').select('id,realm_id,mode,cutoff_date,opening_as_of_date,reconciliation_date,accounting_basis,home_currency,status,opening_journal_id,result,last_error,attempt_count,started_at,completed_at').eq('company_id',companyId).order('created_at',{ascending:false});query=id?query.eq('id',id):query.limit(20);const result=await query;if(result.error)throw result.error;return result.data??[]}
