import PDFDocument from 'pdfkit'
import { authzErrorResponse } from '@/lib/authz'
import { requireAccountingRead } from '@/lib/product-parity/permissions'
import { certificationCsv } from '@/lib/quickbooks-certification/engine'
import { isQuickBooksCertificationEnabled, quickBooksCertificationDisabledResponse } from '@/lib/quickbooks-certification/feature'
import { getCertificationReports } from '@/lib/quickbooks-certification/service'
import type { AccountingCertificationReport } from '@/lib/quickbooks-certification/types'

function pdf(report:AccountingCertificationReport):Promise<Buffer>{return new Promise((resolve,reject)=>{const document=new PDFDocument({size:'A4',margin:42});const chunks:Buffer[]=[];document.on('data',(chunk:Buffer)=>chunks.push(chunk));document.on('end',()=>resolve(Buffer.concat(chunks)));document.on('error',reject);document.font('Helvetica-Bold').fontSize(20).text('QuickBooks Migration Certification');document.moveDown(0.4).font('Helvetica').fontSize(10).text(`Status: ${report.status}`).text(`Realm: ${report.realmId}`).text(`Generated: ${report.generatedAt}`).text(`Period: ${report.parameters.startDate} to ${report.parameters.endDate} (${report.parameters.accountingBasis})`).text(`Tolerance: ${report.parameters.exact?'Exact':`${report.parameters.absoluteTolerance} absolute / ${report.parameters.relativeTolerance*100}% relative`}`);document.moveDown();for(const section of report.sections){document.font('Helvetica-Bold').fontSize(11).text(`${section.label}: ${section.status}`);document.font('Helvetica').fontSize(9).text(`${section.matchedRows}/${section.comparedRows} rows matched; maximum difference ${section.maximumDifference}`);if(section.error)document.fillColor('#b91c1c').text(section.error).fillColor('#000000');for(const difference of section.differences.slice(0,20))document.text(`${difference.label} / ${difference.metric}: QuickBooks ${difference.quickBooksValue}, Hisab ${difference.hisabValue}, difference ${difference.difference}`);if(section.differences.length>20)document.text(`… ${section.differences.length-20} additional differences are available in JSON/CSV.`);document.moveDown(0.6);if(document.y>document.page.height-90)document.addPage()}document.end()})}

export async function GET(request:Request,{params}:{params:Promise<{runId:string}>}){if(!isQuickBooksCertificationEnabled())return quickBooksCertificationDisabledResponse();try{const user=await requireAccountingRead();const {runId}=await params;const rows=await getCertificationReports(user.companyId,runId);const stored=rows[0];if(!stored?.report)return Response.json({error:'Certification report not found.'},{status:404});const report=stored.report as AccountingCertificationReport;const format=new URL(request.url).searchParams.get('format')??'json';const filename=`quickbooks-certification-${runId}`;if(format==='json')return new Response(JSON.stringify(report,null,2),{headers:{'Content-Type':'application/json','Content-Disposition':`attachment; filename="${filename}.json"`}});if(format==='csv')return new Response(certificationCsv(report.sections),{headers:{'Content-Type':'text/csv; charset=utf-8','Content-Disposition':`attachment; filename="${filename}.csv"`}});if(format==='pdf'){const content=await pdf(report);return new Response(new Uint8Array(content),{headers:{'Content-Type':'application/pdf','Content-Disposition':`attachment; filename="${filename}.pdf"`}})}return Response.json({error:'format must be json, csv, or pdf.'},{status:400})}catch(error){return authzErrorResponse(error)}}
