import 'server-only'
import type { AccountingProvider,ProviderAccessContext } from '@/integrations/accounting/contracts/accounting-provider'
import { createAdminClient } from '@/lib/supabase/admin'
import { normalizedKey } from './engine'
import { compareFxRows,parseQuickBooksFxGeneralLedger,type FxComparableRow } from './multicurrency-engine'
import type { QuickBooksFxLedgerRow } from './multicurrency-engine'
import type { CertificationAuxiliaryKey,CertificationDifference,CertificationParameters,CertificationSection } from './types'

type Row=Record<string,unknown>
const TRANSACTIONS=['Invoice','Bill','Payment','BillPayment','Purchase','JournalEntry','SalesReceipt','CreditMemo','VendorCredit','Deposit','Transfer','RefundReceipt','InventoryAdjustment']
const num=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
const obj=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{}
const currencyOf=(record:Row,payload:Row,home:string)=>String(record.currency_code??obj(payload.CurrencyRef).value??home).toUpperCase()
const dateOf=(payload:Row)=>String(payload.TxnDate??payload.TxnDateTime??obj(payload.MetaData).CreateTime??'').slice(0,10)
function totalOf(payload:Row){if(payload.TotalAmt!==undefined)return num(payload.TotalAmt);if(payload.Amount!==undefined)return num(payload.Amount);const lines=Array.isArray(payload.Line)?payload.Line as Row[]:[];return lines.reduce((sum,line)=>sum+Math.max(num(line.Amount),num(line.Debit),num(line.Credit)),0)}
function forcedFailure(key:CertificationAuxiliaryKey,label:string,metric:string,message:string,count=1):CertificationDifference{return {reportKey:key,key:metric,label,metric,quickBooksValue:0,hisabValue:count,difference:count,materiality:0,severity:'ERROR',recommendedAction:message}}
function addFailures(section:CertificationSection,failures:CertificationDifference[]){section.differences.push(...failures);if(failures.length)section.status='FAILED';section.comparedRows+=failures.length;section.maximumDifference=Math.max(section.maximumDifference,...failures.map(item=>Math.abs(item.difference)))}
// Supabase's dynamic-table builder is intentionally erased here; returned rows are normalized immediately.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function pages(table:string,build:(query:any)=>any){const db=createAdminClient(),rows:Row[]=[];for(let from=0;;from+=1000){const result=await build(db.from(table).select('*')).range(from,from+999);if(result.error)throw result.error;rows.push(...((result.data??[]) as Row[]));if((result.data?.length??0)<1000)break}return rows}
const aggregate=(rows:FxComparableRow[])=>{const map=new Map<string,FxComparableRow>();for(const row of rows){const current=map.get(row.key)??{...row,values:{}};for(const [key,value] of Object.entries(row.values))current.values[key]=(current.values[key]??0)+value;map.set(row.key,current)}return [...map.values()]}
async function fetchFxLedger(provider:AccountingProvider,context:ProviderAccessContext,parameters:CertificationParameters){const periods:Array<{start:string;end:string}>=[];let cursor=new Date(`${parameters.startDate}T00:00:00.000Z`);const last=new Date(`${parameters.endDate}T00:00:00.000Z`);while(cursor<=last){const end=new Date(Date.UTC(cursor.getUTCFullYear(),cursor.getUTCMonth()+6,0)),bounded=end>last?last:end;periods.push({start:cursor.toISOString().slice(0,10),end:bounded.toISOString().slice(0,10)});cursor=new Date(Date.UTC(bounded.getUTCFullYear(),bounded.getUTCMonth(),bounded.getUTCDate()+1))}const rows:QuickBooksFxLedgerRow[]=[];let missingForeignEvidence=0,reportCurrency:string|null=null;for(let offset=0;offset<periods.length;offset+=3){const batch=await Promise.all(periods.slice(offset,offset+3).map(period=>provider.getReports!(context,[{reportName:'GeneralLedgerDetail',parameters:{start_date:period.start,end_date:period.end,accounting_method:parameters.accountingBasis,columns:'tx_date,txn_type,doc_num,memo,account_name,currency,exch_rate,foreign_amount,amount'}}])));for(let index=0;index<batch.length;index++){const parsed=parseQuickBooksFxGeneralLedger(batch[index].GeneralLedgerDetail,parameters.homeCurrency);reportCurrency=reportCurrency??parsed.reportCurrency;missingForeignEvidence+=parsed.missingForeignEvidence;const first=offset+index===0;rows.push(...parsed.rows.filter(row=>first||!/^beginning balance$/i.test(row.transactionType.trim())))}}return {rows,missingForeignEvidence,reportCurrency}}

export async function certifyMultiCurrency(input:{companyId:string;realmId:string;provider:AccountingProvider;context:ProviderAccessContext;parameters:CertificationParameters}):Promise<CertificationSection[]>{
  const {companyId,realmId,provider,context,parameters}=input,db=createAdminClient(),from=`${parameters.startDate}T00:00:00.000Z`,to=`${parameters.endDate}T23:59:59.999Z`
  if(!provider.getReports)throw new Error('QuickBooks reports are required for multi-currency certification.')
  const [records,runs,ledgerResult,accountResult,currencies,rates,settings,accounts,revaluations,revaluationLines,parsed]=await Promise.all([
    pages('quickbooks_migration_records',q=>q.eq('company_id',companyId).eq('realm_id',realmId).in('entity_type',[...TRANSACTIONS,'ExchangeRate','Account']).eq('is_deleted',false)),
    pages('quickbooks_materialization_runs',q=>q.eq('company_id',companyId).eq('realm_id',realmId)),
    db.rpc('certification_fx_ledger_by_source',{p_company_id:companyId,p_from:from,p_to:to}),
    db.rpc('certification_fx_account_balances',{p_company_id:companyId,p_from:from,p_to:to}),
    pages('company_currencies',q=>q.eq('company_id',companyId).eq('is_active',true)),
    pages('exchange_rates',q=>q.eq('company_id',companyId).gte('effective_date',from).lte('effective_date',to)),
    db.from('currency_settings').select('*').eq('company_id',companyId).maybeSingle(),
    pages('chart_of_accounts',q=>q.eq('company_id',companyId).is('deleted_at',null)),
    pages('fx_revaluations',q=>q.eq('company_id',companyId).gte('revaluation_date',from).lte('revaluation_date',to).eq('status','POSTED')),
    pages('fx_revaluation_lines',q=>q.eq('company_id',companyId)),
    fetchFxLedger(provider,context,parameters),
  ])
  if(ledgerResult.error)throw ledgerResult.error;if(accountResult.error)throw accountResult.error;if(settings.error)throw settings.error
  const home=parameters.homeCurrency.toUpperCase(),runBySource=new Map(runs.map(row=>[`${row.entity_type}:${row.source_id}`,row])),ledgerBySource=new Map<string,Row[]>()
  for(const row of (ledgerResult.data??[]) as Row[]){const key=String(row.source_id);ledgerBySource.set(key,[...(ledgerBySource.get(key)??[]),row])}
  const foreignRecords=records.filter(record=>TRANSACTIONS.includes(String(record.entity_type))).filter(record=>{const payload=obj(record.source_payload),date=dateOf(payload);return date>=parameters.startDate&&date<=parameters.endDate&&currencyOf(record,payload,home)!==home})
  const sourceTransactions:FxComparableRow[]=[],hisabTransactions:FxComparableRow[]=[],sourceRates:FxComparableRow[]=[],hisabRates:FxComparableRow[]=[],transactionFailures:CertificationDifference[]=[],rateFailures:CertificationDifference[]=[]
  for(const record of foreignRecords){const payload=obj(record.source_payload),entity=String(record.entity_type),sourceId=String(record.source_id),currency=currencyOf(record,payload,home),date=dateOf(payload),rate=num(payload.ExchangeRate??record.exchange_rate),total=totalOf(payload),homeTotal=num(payload.HomeTotalAmt??total*rate),run=runBySource.get(`${entity}:${sourceId}`),localId=String(record.local_id??run?.local_id??''),ledger=ledgerBySource.get(localId)??[],matching=ledger.filter(row=>String(row.currency).toUpperCase()===currency),key=`${entity}:${sourceId}:${currency}`
    sourceTransactions.push({key,label:`${entity} ${sourceId}`,currency,sourceId,values:{transactionAmount:Math.abs(total),homeAmount:Math.abs(homeTotal),exchangeRate:rate}})
    const transactionDebit=matching.reduce((sum,row)=>sum+num(row.transaction_debit),0),transactionCredit=matching.reduce((sum,row)=>sum+num(row.transaction_credit),0),baseDebit=matching.reduce((sum,row)=>sum+num(row.base_debit),0),baseCredit=matching.reduce((sum,row)=>sum+num(row.base_credit),0),minimumRate=matching.length?Math.min(...matching.map(row=>num(row.minimum_rate))):0,maximumRate=matching.length?Math.max(...matching.map(row=>num(row.maximum_rate))):0
    hisabTransactions.push({key,label:`${entity} ${sourceId}`,currency,localId,values:{transactionAmount:Math.max(Math.abs(transactionDebit),Math.abs(transactionCredit)),homeAmount:Math.max(Math.abs(baseDebit),Math.abs(baseCredit)),exchangeRate:minimumRate===maximumRate?minimumRate:maximumRate}})
    if(!localId||!matching.length)transactionFailures.push(forcedFailure('fx-transactions',`${entity} ${sourceId}`,'missing-ledger',`Materialize the ${currency} transaction and its native ledger posting.`))
    if(matching.some(row=>num(row.invalid_rate_count)>0)||minimumRate!==maximumRate)transactionFailures.push(forcedFailure('fx-transactions',`${entity} ${sourceId}`,'ledger-rate-integrity','Every ledger line for a source transaction must use the same positive QuickBooks exchange rate.'))
    const rateKey=`${currency}:${date}:${entity}:${sourceId}`;sourceRates.push({key:rateKey,label:`${currency} rate on ${date}`,currency,sourceId,values:{rate}});hisabRates.push({key:rateKey,label:`${currency} rate on ${date}`,currency,localId,values:{rate:minimumRate===maximumRate?minimumRate:maximumRate}})
  }
  const storedRateMap=new Map(rates.map(row=>[`${String(row.from_currency).toUpperCase()}:${String(row.to_currency).toUpperCase()}:${String(row.effective_date).slice(0,10)}`,num(row.rate)]))
  for(const record of records.filter(row=>String(row.entity_type)==='ExchangeRate')){const payload=obj(record.source_payload),fromCurrency=String(payload.SourceCurrencyCode??obj(payload.SourceCurrencyRef).value??'').toUpperCase(),target=String(payload.TargetCurrencyCode??obj(payload.TargetCurrencyRef).value??home).toUpperCase(),date=String(payload.AsOfDate??'').slice(0,10),rate=num(payload.Rate??record.exchange_rate),key=`official:${fromCurrency}:${target}:${date}`;sourceRates.push({key,label:`${fromCurrency}/${target} ${date}`,currency:fromCurrency,sourceId:String(record.source_id),values:{rate}});hisabRates.push({key,label:`${fromCurrency}/${target} ${date}`,currency:fromCurrency,values:{rate:storedRateMap.get(`${fromCurrency}:${target}:${date}`)??0}})}
  if(foreignRecords.length&&!sourceRates.length)rateFailures.push(forcedFailure('fx-exchange-rates','Historical exchange rates','missing-source-evidence','Extract QuickBooks transaction exchange rates before multi-currency certification.'))
  const transactionSection=compareFxRows('fx-transactions','Transaction and home currency amounts',sourceTransactions,hisabTransactions,parameters);addFailures(transactionSection,transactionFailures)
  const rateSection=compareFxRows('fx-exchange-rates','Historical exchange rates',sourceRates,hisabRates,parameters);addFailures(rateSection,rateFailures)

  const sourceBalances=aggregate(parsed.rows.filter(row=>row.account&&(row.currency===home||row.foreignAmount!==null)).map(row=>({key:normalizedKey(`${row.account}|${row.currency}`),label:`${row.account} (${row.currency})`,currency:row.currency,sourceId:row.sourceId,values:{transactionBalance:row.currency===home?row.homeAmount:(row.foreignAmount??0),homeBalance:row.homeAmount}}))),hisabBalances=aggregate(((accountResult.data??[]) as Row[]).map(row=>({key:normalizedKey(`${row.account_name}|${row.currency}`),label:`${row.account_name} (${row.currency})`,currency:String(row.currency),localId:String(row.account_id),values:{transactionBalance:num(row.transaction_debit)-num(row.transaction_credit),homeBalance:num(row.base_debit)-num(row.base_credit)}})))
  const balanceSection=compareFxRows('fx-currency-balances','Per-currency account balances',sourceBalances,hisabBalances,parameters),balanceFailures:CertificationDifference[]=[]
  if(parsed.reportCurrency&&parsed.reportCurrency!==home)balanceFailures.push(forcedFailure('fx-currency-balances','QuickBooks General Ledger','report-home-currency',`Generate the QuickBooks ledger in home currency ${home}.`))
  if(parsed.missingForeignEvidence)balanceFailures.push(forcedFailure('fx-currency-balances','QuickBooks General Ledger','missing-foreign-amount',`${parsed.missingForeignEvidence} QuickBooks ledger rows did not return foreign-currency amounts.`,parsed.missingForeignEvidence))
  const expectedCurrencies=new Set([home,...currencies.map(row=>String(row.code).toUpperCase()),...foreignRecords.map(row=>currencyOf(row,obj(row.source_payload),home))]);for(const currency of expectedCurrencies)if(currency!==home&&!sourceBalances.some(row=>row.currency===currency))balanceFailures.push(forcedFailure('fx-currency-balances',currency,'missing-currency-balance',`QuickBooks did not return authoritative General Ledger currency balances for ${currency}.`))
  addFailures(balanceSection,balanceFailures)

  const accountById=new Map(accounts.map(row=>[String(row.id),row])),setting=settings.data as Row|null,roles=[['realized_gain_account_id','Realized FX gain'],['realized_loss_account_id','Realized FX loss'],['unrealized_gain_account_id','Unrealized FX gain'],['unrealized_loss_account_id','Unrealized FX loss']] as const,accountSource:FxComparableRow[]=[],accountHisab:FxComparableRow[]=[]
  for(const [field,label] of roles){const id=String(setting?.[field]??'');accountSource.push({key:field,label,currency:home,values:{configured:1}});accountHisab.push({key:field,label,currency:home,localId:id||undefined,values:{configured:id&&accountById.has(id)?1:0}})}
  const accountsSection=compareFxRows('fx-accounts','Currency gain/loss accounts',accountSource,accountHisab,parameters)
  const accountBalances=(accountResult.data??[]) as Row[],fxAccountIds=new Set(roles.map(([field])=>String(setting?.[field]??'')).filter(Boolean))
  const hisabFx=(classification:'REALIZED'|'UNREALIZED')=>{const wanted=new Set(roles.filter(([field])=>field.startsWith(classification.toLowerCase())).map(([field])=>String(setting?.[field]??'')));return aggregate(accountBalances.filter(row=>wanted.has(String(row.account_id))).map(row=>({key:`${classification.toLowerCase()}:${String(row.currency)}`,label:`${classification.toLowerCase()} FX (${row.currency})`,currency:String(row.currency),localId:String(row.account_id),values:{homeAmount:num(row.base_debit)-num(row.base_credit)}})))}
  const sourceFx=(classification:'REALIZED'|'UNREALIZED')=>aggregate(parsed.rows.filter(row=>row.isFxAccount&&row.classification===classification).map(row=>({key:`${classification.toLowerCase()}:${row.currency}`,label:`${classification.toLowerCase()} FX (${row.currency})`,currency:row.currency,sourceId:row.sourceId,values:{homeAmount:row.homeAmount}})))
  const realizedSection=compareFxRows('fx-realized','Realized currency gains and losses',sourceFx('REALIZED'),hisabFx('REALIZED'),parameters),unrealizedSection=compareFxRows('fx-unrealized','Unrealized currency gains and losses',sourceFx('UNREALIZED'),hisabFx('UNREALIZED'),parameters)
  if(foreignRecords.length&&fxAccountIds.size<4)addFailures(accountsSection,[forcedFailure('fx-accounts','Currency gain/loss accounts','incomplete-settings','Configure all four realized and unrealized FX gain/loss accounts.')])
  const revaluationById=new Map(revaluations.map(row=>[String(row.id),row])),sourceRevaluations=aggregate(parsed.rows.filter(row=>row.classification==='UNREALIZED'&&!row.isFxAccount).map(row=>({key:`${row.date}:${row.currency}`,label:`QuickBooks revaluation ${row.date} ${row.currency}`,currency:row.currency,sourceId:row.sourceId,values:{adjustment:row.homeAmount}}))),hisabRevaluations=aggregate(revaluationLines.filter(line=>revaluationById.has(String(line.revaluation_id))).map(line=>{const header=revaluationById.get(String(line.revaluation_id))!;return {key:`${String(header.revaluation_date).slice(0,10)}:${String(line.currency).toUpperCase()}`,label:`Hisab revaluation ${String(header.revaluation_date).slice(0,10)} ${line.currency}`,currency:String(line.currency).toUpperCase(),localId:String(line.revaluation_id),values:{adjustment:num(line.adjustment_amount)}}}))
  const revaluationSection=compareFxRows('fx-revaluations','Revaluation entries',sourceRevaluations,hisabRevaluations,parameters)
  return [rateSection,transactionSection,balanceSection,realizedSection,unrealizedSection,revaluationSection,accountsSection]
}
