import 'server-only'
import { createAdminClient } from '@/lib/supabase/admin'
import { extractQuickBooksPaymentRelationships } from '@/lib/import-export/quickbooks/payment-relationships'
import { compareFxRows,type FxComparableRow } from './multicurrency-engine'
import type { CertificationDifference,CertificationParameters,CertificationSection } from './types'

type Row=Record<string,unknown>
const object=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{}
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
// Supabase dynamic table pagination is normalized immediately.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function pages(table:string,build:(query:any)=>any){const db=createAdminClient(),rows:Row[]=[];for(let from=0;;from+=1000){const result=await build(db.from(table).select('*')).range(from,from+999);if(result.error)throw result.error;rows.push(...((result.data??[]) as Row[]));if((result.data?.length??0)<1000)break}return rows}

export async function certifyPaymentAllocations(companyId:string,realmId:string,parameters:CertificationParameters):Promise<CertificationSection>{
  const [records,allocations,payments]=await Promise.all([pages('quickbooks_migration_records',q=>q.eq('company_id',companyId).eq('realm_id',realmId).in('entity_type',['Payment','BillPayment']).eq('is_deleted',false)),pages('payment_allocations',q=>q.eq('company_id',companyId).eq('source_system','QUICKBOOKS')),pages('payments',q=>q.eq('company_id',companyId).is('deleted_at',null))])
  const source:FxComparableRow[]=[],local:FxComparableRow[]=[],failures:CertificationDifference[]=[],paymentById=new Map(payments.map(item=>[String(item.id),item])),localBySource=new Map(allocations.map(item=>[`${item.invoice_id?'Payment':'BillPayment'}:${item.source_payment_id}:${item.source_line_key}:${item.source_target_id}`,item]))
  for(const record of records){const entity=String(record.entity_type),sourceId=String(record.source_id),relationships=extractQuickBooksPaymentRelationships(object(record.source_payload),entity==='BillPayment'?'VENDOR':'CUSTOMER'),prefix=`${entity}:${sourceId}`
    source.push({key:`${prefix}:summary`,label:`${entity} ${sourceId} summary`,currency:String(record.currency_code??parameters.homeCurrency),sourceId,values:{paymentAmount:relationships.paymentAmount,appliedAmount:relationships.appliedAmount,creditAppliedAmount:relationships.creditAppliedAmount,unappliedAmount:relationships.unappliedAmount}})
    for(const issue of relationships.issues)failures.push({reportKey:'payment-allocations',key:`${prefix}:evidence`,label:`${entity} ${sourceId}`,metric:'relationshipEvidence',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:issue,sourceRefs:[{sourceId}]})
    for(const item of relationships.allocations){const key=`${prefix}:${item.sourceLineKey}:${item.targetSourceId}`,matched=localBySource.get(key),sourceCredits=[...item.creditSourceIds].sort(),localCredits=Array.isArray(matched?.source_credit_ids)?matched.source_credit_ids.map(String).sort():[];source.push({key,label:`${entity} ${sourceId} → ${item.targetType} ${item.targetSourceId}`,currency:String(record.currency_code??parameters.homeCurrency),sourceId,values:{amount:item.amount,cashAmount:item.cashAmount,creditAmount:item.creditAmount,creditRelationships:sourceCredits.length}});if(JSON.stringify(sourceCredits)!==JSON.stringify(localCredits))failures.push({reportKey:'payment-allocations',key,label:`${entity} ${sourceId} credit relationships`,metric:'creditSourceIds',quickBooksValue:sourceCredits.length,hisabValue:localCredits.length,difference:localCredits.length-sourceCredits.length,materiality:0,severity:'ERROR',recommendedAction:`Expected credits [${sourceCredits.join(', ')}], found [${localCredits.join(', ')}].`,sourceRefs:[{sourceId,documentId:matched?String(matched.payment_id):undefined}]})}
  }
  const grouped=new Map<string,Row[]>();for(const allocation of allocations){const entity=allocation.invoice_id?'Payment':'BillPayment',key=`${entity}:${allocation.source_payment_id}`,current=grouped.get(key)??[];current.push(allocation);grouped.set(key,current);local.push({key:`${key}:${allocation.source_line_key}:${allocation.source_target_id}`,label:`${entity} ${allocation.source_payment_id} → ${allocation.source_target_id}`,currency:String(allocation.currency),localId:String(allocation.payment_id),values:{amount:number(allocation.amount),cashAmount:number(allocation.cash_amount),creditAmount:number(allocation.credit_amount),creditRelationships:Array.isArray(allocation.source_credit_ids)?allocation.source_credit_ids.length:0}})}
  for(const [key,items] of grouped){const payment=paymentById.get(String(items[0].payment_id));local.push({key:`${key}:summary`,label:`${key} summary`,currency:String(payment?.currency??parameters.homeCurrency),localId:String(payment?.id??''),values:{paymentAmount:number(payment?.amount),appliedAmount:number(payment?.applied_amount),creditAppliedAmount:number(payment?.credit_applied_amount),unappliedAmount:number(payment?.unapplied_amount)}})}
  const section=compareFxRows('payment-allocations','Payment relationships and allocations',source,local,parameters)
  section.differences.push(...failures);if(failures.length)section.status='FAILED';section.comparedRows+=failures.length;return section
}
