import 'server-only'
import type { AccountingProvider,ProviderAccessContext,ProviderReportRequest } from '@/integrations/accounting/contracts/accounting-provider'
import { createAdminClient } from '@/lib/supabase/admin'
import { money,normalizedKey } from './engine'
import { buildFiscalProofPeriods,certifyRetainedEarningsPeriods,partitionReportRange,previousDate,type FiscalProofPeriod,type RetainedEarningsEvidence,type RetainedEarningsPeriodEvidence } from './retained-earnings-engine'
import type { CertificationParameters,CertificationSection } from './types'

type Row=Record<string,unknown>
type ReportRow={label:string;path:string;values:Record<string,number>}
const object=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{}
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
const dayEnd=(date:string)=>new Date(`${date}T23:59:59.999Z`).getTime()
const dayStart=(date:string)=>new Date(`${date}T00:00:00.000Z`).getTime()
const retainedPattern=/\bretained earnings?\b/i,drawPattern=/(owner|partner|member).*(draw|withdraw|distribution)|\bdividends?\b|\bdistributions?\b/i,netIncomePattern=/\bnet (income|earnings|profit|loss)\b/i
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function pages(table:string,build:(query:any)=>any){const db=createAdminClient(),rows:Row[]=[];for(let from=0;;from+=1000){const result=await build(db.from(table).select('*')).order('id').range(from,from+999);if(result.error)throw result.error;rows.push(...((result.data??[]) as Row[]));if((result.data?.length??0)<1000)break}return rows}

function reportRows(payload:unknown,includeSummary=true):ReportRow[]{const root=object(payload),columns=((object(root.Columns).Column??[]) as Row[]),titles=columns.map((column,index)=>normalizedKey(column.ColTitle??column.ColType??`value ${index}`).replaceAll(' ','_')),rows:ReportRow[]=[]
  const add=(cells:Row[],path:string)=>{if(!cells.length)return;const label=String(cells[0]?.value??path),values:Record<string,number>={};for(let index=1;index<cells.length;index++){const raw=cells[index]?.value;if(raw!==undefined&&raw!==null&&String(raw).trim()!==''&&/[0-9]/.test(String(raw)))values[titles[index]??`value_${index}`]=money(raw)}if(Object.keys(values).length)rows.push({label,path,values})}
  const walk=(items:Row[],parent='')=>{for(const item of items){const header=((object(item.Header).ColData??[]) as Row[]),path=String(header[0]?.value??parent);add((item.ColData??[]) as Row[],path);if(includeSummary)add((object(item.Summary).ColData??[]) as Row[],path);walk((object(item.Rows).Row??[]) as Row[],path||parent)}};walk((object(root.Rows).Row??[]) as Row[]);return rows}
const value=(row:ReportRow)=>{const values=Object.values(row.values);return values.length?values.at(-1)!:0}
function validReport(payload:unknown){const root=object(payload),header=object(root.Header),options=(header.Option??[]) as Row[];return Boolean(root.Rows)||options.some(option=>String(option.Name)==='NoReportData'&&String(option.Value)==='true')}
function noReportData(payload:unknown){return ((object(object(payload).Header).Option??[]) as Row[]).some(option=>String(option.Name)==='NoReportData'&&String(option.Value)==='true')}
function balanceSheetEvidence(payload:unknown){const rows=reportRows(payload),retained=rows.filter(row=>retainedPattern.test(row.label)).at(-1),netIncome=rows.filter(row=>netIncomePattern.test(row.label)).at(-1),drawMap=new Map(rows.filter(row=>drawPattern.test(row.label)).map(row=>[normalizedKey(row.label),row])),drawRows=[...drawMap.values()],drawSigned=drawRows.reduce((sum,row)=>sum+value(row),0),drawings=Math.abs(drawSigned);return {retained:number(retained?value(retained):0),netIncome:number(netIncome?value(netIncome):0),drawings,economic:number(retained?value(retained):0)+number(netIncome?value(netIncome):0)-drawings,complete:validReport(payload),evidence:[...new Set([retained?.label,netIncome?.label,...drawRows.map(row=>row.label)].filter(Boolean) as string[])]}}
function profitLossNetIncome(payload:unknown){const rows=reportRows(payload),match=rows.filter(row=>netIncomePattern.test(row.label)).at(-1);return {amount:match?value(match):0,complete:Boolean(match)||noReportData(payload),evidence:match?[match.label]:[]}}
function generalLedgerEquity(payload:unknown){const rows=reportRows(payload,false);let drawings=0,adjustments=0,complete=true;const evidence:string[]=[];for(const row of rows){const account=`${row.path} ${row.label}`;if(/beginning balance|ending balance|total/i.test(row.label))continue;const relevantDraw=drawPattern.test(row.path),relevantRetained=retainedPattern.test(row.path);if(!relevantDraw&&!relevantRetained)continue;const debitKey=Object.keys(row.values).find(key=>/debit/.test(key)),creditKey=Object.keys(row.values).find(key=>/credit/.test(key));if(!debitKey&&!creditKey){complete=false;continue}const debit=number(debitKey?row.values[debitKey]:0),credit=number(creditKey?row.values[creditKey]:0);if(relevantDraw)drawings+=debit-credit;if(relevantRetained)adjustments+=credit-debit;evidence.push(`${account}: debit ${debit}, credit ${credit}`)}return {drawings,adjustments,complete,evidence}}

async function fetchReport(provider:AccountingProvider,context:ProviderAccessContext,request:ProviderReportRequest){if(!provider.getReports)throw new Error('QuickBooks Reports API is unavailable.');const result=await provider.getReports(context,[request]);const payload=result[request.reportName];if(!payload)throw new Error(`QuickBooks ${request.reportName} report returned no evidence.`);return payload}
const request=(reportName:string,startDate:string,endDate:string,parameters:CertificationParameters):ProviderReportRequest=>({reportName,parameters:{start_date:startDate,end_date:endDate,accounting_method:parameters.accountingBasis,currency:parameters.homeCurrency}})

function amount(entry:Row,side:'debit'|'credit'){const base=entry[`base_${side}`];if(base!==null&&base!==undefined)return number(base);return number(entry[side])}
function account(entry:Row){return object(entry.account)}
const entryTime=(entry:Row)=>new Date(String(entry.entry_date)).getTime()
const isRetained=(entry:Row)=>retainedPattern.test(String(account(entry).name??account(entry).full_name??''))
const isDrawing=(entry:Row)=>drawPattern.test(String(account(entry).name??account(entry).full_name??''))
function netIncome(entries:Row[],from:number,to:number){let result=0;for(const entry of entries){const time=entryTime(entry),type=String(account(entry).canonical_type??'');if(time<from||time>to||String(entry.source_type)==='YEAR_CLOSE')continue;const debit=amount(entry,'debit'),credit=amount(entry,'credit');if(type==='Income')result+=credit-debit;else if(type==='Expense'||type==='CostOfGoodsSold')result+=credit-debit}return result}
function drawingMovement(entries:Row[],from:number,to:number){return entries.filter(entry=>isDrawing(entry)&&entryTime(entry)>=from&&entryTime(entry)<=to).reduce((sum,entry)=>sum+amount(entry,'debit')-amount(entry,'credit'),0)}
function retainedMovement(entries:Row[],from:number,to:number,excludedSources:string[]=[]){return entries.filter(entry=>isRetained(entry)&&entryTime(entry)>=from&&entryTime(entry)<=to&&!excludedSources.includes(String(entry.source_type))).reduce((sum,entry)=>sum+amount(entry,'credit')-amount(entry,'debit'),0)}
function retainedSourceMovement(entries:Row[],from:number,to:number,sourceType:string){return entries.filter(entry=>isRetained(entry)&&entryTime(entry)>=from&&entryTime(entry)<=to&&String(entry.source_type)===sourceType).reduce((sum,entry)=>sum+amount(entry,'credit')-amount(entry,'debit'),0)}
function economicBalance(entries:Row[],closings:Row[],at:number){const retained=retainedMovement(entries,Number.MIN_SAFE_INTEGER,at),drawings=drawingMovement(entries,Number.MIN_SAFE_INTEGER,at),operating=netIncome(entries,Number.MIN_SAFE_INTEGER,at),closed=closings.filter(close=>new Date(String(close.period_end)).getTime()<=at).reduce((sum,close)=>sum+number(close.net_income),0);return retained+(operating-closed)-drawings}

async function quickBooksEvidence(provider:AccountingProvider,context:ProviderAccessContext,period:FiscalProofPeriod,parameters:CertificationParameters):Promise<RetainedEarningsEvidence>{const openingPayload=await fetchReport(provider,context,request('BalanceSheet','1900-01-01',previousDate(period.startDate),parameters)),closingPayload=await fetchReport(provider,context,request('BalanceSheet','1900-01-01',period.endDate,parameters)),opening=balanceSheetEvidence(openingPayload),closing=balanceSheetEvidence(closingPayload);let historicalNetIncome=0,ownerDrawings=0,adjustments=0,complete=opening.complete&&closing.complete;const evidence=[...opening.evidence,...closing.evidence]
  for(const chunk of partitionReportRange(period.startDate,period.endDate)){const [plPayload,glPayload]=await Promise.all([fetchReport(provider,context,request('ProfitAndLoss',chunk.startDate,chunk.endDate,parameters)),fetchReport(provider,context,request('GeneralLedgerDetail',chunk.startDate,chunk.endDate,parameters))]),pl=profitLossNetIncome(plPayload),gl=generalLedgerEquity(glPayload);historicalNetIncome+=pl.amount;ownerDrawings+=gl.drawings;adjustments+=gl.adjustments;complete=complete&&pl.complete&&gl.complete;evidence.push(...pl.evidence,...gl.evidence)}
  return {openingEquity:opening.economic,historicalNetIncome,ownerDrawings,adjustments,retainedEarnings:closing.economic,proofComplete:complete,evidence:[...new Set(evidence)],breakdown:{openingRetainedEarnings:opening.retained,openingCurrentNetIncome:opening.netIncome,closingRetainedEarnings:closing.retained,closingCurrentNetIncome:closing.netIncome,directRetainedAdjustments:adjustments}}}

export async function certifyRetainedEarnings(input:{companyId:string;realmId:string;runId:string;provider:AccountingProvider;context:ProviderAccessContext;parameters:CertificationParameters}):Promise<CertificationSection>{const db=createAdminClient(),[companyResult,entryRows,closeRows,periodRows,cutoffResult]=await Promise.all([db.from('companies').select('fiscal_year_start').eq('id',input.companyId).single(),pages('ledger_entries',query=>query.eq('company_id',input.companyId).lte('entry_date',`${input.parameters.asOfDate}T23:59:59.999Z`)),pages('fiscal_year_closings',query=>query.eq('company_id',input.companyId)),pages('fiscal_periods',query=>query.eq('company_id',input.companyId)),db.from('quickbooks_cutoff_reconciliations').select('id,mode,cutoff_date,reconciliation_date,status').eq('company_id',input.companyId).eq('realm_id',input.realmId).lte('reconciliation_date',input.parameters.asOfDate).order('reconciliation_date',{ascending:false}).limit(1).maybeSingle()]);if(companyResult.error)throw companyResult.error;if(cutoffResult.error)throw cutoffResult.error
  const accounts=await pages('chart_of_accounts',query=>query.eq('company_id',input.companyId).is('deleted_at',null)),accountMap=new Map(accounts.map(item=>[String(item.id),item]));for(const entry of entryRows)entry.account=accountMap.get(String(entry.account_id))??{}
  const periodById=new Map(periodRows.map(item=>[String(item.id),item]));for(const close of closeRows){const period=periodById.get(String(close.period_id));if(period)close.period_end=period.period_end}
  const periods=buildFiscalProofPeriods(input.parameters.startDate,input.parameters.asOfDate,String(companyResult.data.fiscal_year_start??'01-01')),cutoff=cutoffResult.data,rows:RetainedEarningsPeriodEvidence[]=[]
  for(const original of periods){const period={...original};let cutoffBasis:string|null=null;if(cutoff&&period.startDate<String(cutoff.mode==='OPENING_BALANCE_ONLY'?cutoff.reconciliation_date:cutoff.cutoff_date)&&period.endDate>=String(cutoff.mode==='OPENING_BALANCE_ONLY'?cutoff.reconciliation_date:cutoff.cutoff_date)){period.startDate=String(cutoff.mode==='OPENING_BALANCE_ONLY'?cutoff.reconciliation_date:cutoff.cutoff_date);cutoffBasis=`${cutoff.mode}:${cutoff.id}`}if(period.endDate<period.startDate)continue
    const from=dayStart(period.startDate),to=dayEnd(period.endDate),openingBefore=dayEnd(previousDate(period.startDate)),openingEntries=retainedSourceMovement(entryRows,from,dayEnd(period.startDate),'OPENING_BALANCE'),opening=economicBalance(entryRows,closeRows,openingBefore)+openingEntries,periodIncome=netIncome(entryRows,from,to),drawings=drawingMovement(entryRows,from,to),adjustments=retainedMovement(entryRows,from,to,['YEAR_CLOSE','OPENING_BALANCE']),priorPeriodAdjustments=retainedSourceMovement(entryRows,from,to,'ADJUSTMENT'),closing=economicBalance(entryRows,closeRows,to),close=closeRows.find(item=>item.period_end&&new Date(String(item.period_end)).getTime()>=from&&new Date(String(item.period_end)).getTime()<=to),closeRequired=original.isComplete,closeIncome=close?number(close.net_income):0,closeLedger=close?retainedSourceMovement(entryRows,from,to,'YEAR_CLOSE'):0,fiscalCloseProven=!closeRequired||Boolean(close&&close.closing_journal_id&&close.opening_journal_id&&Math.abs(closeIncome-periodIncome)<=input.parameters.absoluteTolerance&&Math.abs(closeLedger-periodIncome)<=input.parameters.absoluteTolerance),relevantEntries=entryRows.filter(entry=>entryTime(entry)>=from&&entryTime(entry)<=to&&(isRetained(entry)||isDrawing(entry))).map(entry=>`${String(entry.entry_date).slice(0,10)} ${entry.source_type}:${entry.source_id??entry.id} ${String(account(entry).name??'Equity')} debit ${amount(entry,'debit')} credit ${amount(entry,'credit')}`),hisab:RetainedEarningsEvidence={openingEquity:opening,historicalNetIncome:periodIncome,ownerDrawings:drawings,adjustments,retainedEarnings:closing,proofComplete:Boolean(accounts.some(item=>retainedPattern.test(String(item.name??item.full_name??''))))&&Boolean(!cutoff||cutoff.status==='PASSED'),evidence:[`Ledger ${period.startDate} through ${period.endDate}`,...relevantEntries,...(close?[`Fiscal close ${close.id}`]:[]),...(cutoffBasis?[`Cutoff ${cutoffBasis}`]:[])],breakdown:{cutoffOrOpeningEntries:openingEntries,priorPeriodAdjustments,otherDirectAdjustments:adjustments-priorPeriodAdjustments,fiscalCloseTransfer:closeLedger}},quickBooks=await quickBooksEvidence(input.provider,input.context,period,input.parameters);rows.push({period,quickBooks,hisab,fiscalCloseRequired:closeRequired,fiscalCloseProven,cutoffBasis})}
  const section=certifyRetainedEarningsPeriods(rows,input.parameters),differences=section.differences
  const cleared=await db.from('quickbooks_retained_earnings_periods').delete().eq('run_id',input.runId).eq('company_id',input.companyId);if(cleared.error)throw cleared.error
  if(rows.length){const saved=await db.from('quickbooks_retained_earnings_periods').insert(rows.map(row=>({run_id:input.runId,company_id:input.companyId,realm_id:input.realmId,period_key:row.period.key,period_label:row.period.label,period_start:row.period.startDate,period_end:row.period.endDate,quickbooks_evidence:row.quickBooks,hisab_evidence:row.hisab,fiscal_close_required:row.fiscalCloseRequired,fiscal_close_proven:row.fiscalCloseProven,cutoff_basis:row.cutoffBasis??null,status:differences.some(item=>item.key.startsWith(`${row.period.key}:`))?'FAILED':'MATCHED',differences:differences.filter(item=>item.key.startsWith(`${row.period.key}:`))})));if(saved.error)throw saved.error}
  return section
}
