import 'server-only'
import { createAdminClient } from '@/lib/supabase/admin'
import { compareFxRows,type FxComparableRow } from './multicurrency-engine'
import type { CertificationDifference,CertificationParameters,CertificationSection } from './types'

type Row=Record<string,unknown>
const object=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{}
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function pages(table:string,build:(query:any)=>any){const db=createAdminClient(),rows:Row[]=[];for(let from=0;;from+=1000){const result=await build(db.from(table).select('*')).range(from,from+999);if(result.error)throw result.error;rows.push(...((result.data??[]) as Row[]));if((result.data?.length??0)<1000)break}return rows}

export async function certifySalesReceipts(companyId:string,realmId:string,parameters:CertificationParameters):Promise<CertificationSection>{
  const [records,receipts,lines,ledger,movements,inventoryLedger,accounts]=await Promise.all([
    pages('quickbooks_migration_records',q=>q.eq('company_id',companyId).eq('realm_id',realmId).eq('entity_type','SalesReceipt').eq('is_deleted',false)),pages('sales_receipts',q=>q.eq('company_id',companyId).is('deleted_at',null)),pages('sales_receipt_lines',q=>q.eq('company_id',companyId)),pages('ledger_entries',q=>q.eq('company_id',companyId).eq('source_type','SALES_RECEIPT')),pages('stock_movements',q=>q.eq('company_id',companyId).eq('source_type','SALES_RECEIPT')),pages('ledger_entries',q=>q.eq('company_id',companyId).eq('source_type','INVENTORY')),pages('chart_of_accounts',q=>q.eq('company_id',companyId).is('deleted_at',null)),
  ])
  const bySource=new Map(receipts.map(item=>[String(item.legacy_id),item])),byReceipt=new Map<string,Row[]>(),ledgerByReceipt=new Map<string,Row[]>(),movesByReceipt=new Map<string,Row[]>(),ledgerByMovement=new Map<string,Row[]>(),accountById=new Map(accounts.map(item=>[String(item.id),item]))
  for(const line of lines){const list=byReceipt.get(String(line.sales_receipt_id))??[];list.push(line);byReceipt.set(String(line.sales_receipt_id),list)}for(const line of ledger){const list=ledgerByReceipt.get(String(line.source_id))??[];list.push(line);ledgerByReceipt.set(String(line.source_id),list)}for(const movement of movements){const list=movesByReceipt.get(String(movement.source_id))??[];list.push(movement);movesByReceipt.set(String(movement.source_id),list)}for(const line of inventoryLedger){const list=ledgerByMovement.get(String(line.source_id))??[];list.push(line);ledgerByMovement.set(String(line.source_id),list)}
  const source:FxComparableRow[]=[],local:FxComparableRow[]=[],failures:CertificationDifference[]=[]
  for(const record of records){const sourceId=String(record.source_id),raw=object(record.source_payload),sourceLines=(Array.isArray(raw.Line)?raw.Line:[]).map(object).filter(line=>String(line.DetailType)==='SalesItemLineDetail'),receipt=bySource.get(sourceId),currency=String(record.currency_code??parameters.homeCurrency).toUpperCase(),tax=number(object(raw.TxnTaxDetail).TotalTax),total=number(raw.TotalAmt),subtotal=number(raw.SubTotal??total-tax)
    source.push({key:`SalesReceipt:${sourceId}:summary`,label:`Sales Receipt ${sourceId}`,currency,sourceId,values:{subtotal,tax,total,lines:sourceLines.length}})
    if(receipt){const localLines=(byReceipt.get(String(receipt.id))??[]).sort((a,b)=>number(a.line_no)-number(b.line_no));local.push({key:`SalesReceipt:${sourceId}:summary`,label:`Sales Receipt ${sourceId}`,currency:String(receipt.currency),localId:String(receipt.id),values:{subtotal:number(receipt.subtotal),tax:number(receipt.tax_amount),total:number(receipt.total),lines:localLines.length}})
      const receiptLedger=ledgerByReceipt.get(String(receipt.id))??[],debits=receiptLedger.reduce((sum,item)=>sum+number(item.debit),0),credits=receiptLedger.reduce((sum,item)=>sum+number(item.credit),0),depositDebit=receiptLedger.filter(item=>String(item.account_id)===String(receipt.deposit_account_id)).reduce((sum,item)=>sum+number(item.debit),0),arAmount=receiptLedger.filter(item=>String(accountById.get(String(item.account_id))?.name??'').toLowerCase().includes('receivable')).reduce((sum,item)=>sum+number(item.debit)+number(item.credit),0)
      if(Math.abs(debits-credits)>0.0001||Math.abs(depositDebit-total)>0.0001||arAmount>0.0001)failures.push({reportKey:'sales-receipt-reconciliation',key:`SalesReceipt:${sourceId}:ledger`,label:`Sales Receipt ${sourceId} ledger`,metric:'paidSalePosting',quickBooksValue:total,hisabValue:depositDebit,difference:depositDebit-total,materiality:parameters.absoluteTolerance,severity:'ERROR',recommendedAction:'Regenerate the paid-sale ledger: debit the exact deposit account, credit revenue and tax, and do not post Accounts Receivable.',sourceRefs:[{sourceId,documentId:String(receipt.id)}]})
      const receiptMovements=movesByReceipt.get(String(receipt.id))??[],expectedInventory=localLines.filter(item=>item.inventory_item_id).reduce((sum,item)=>sum+number(item.quantity),0),actualInventory=Math.abs(receiptMovements.reduce((sum,item)=>sum+number(item.quantity),0));if(Math.abs(expectedInventory-actualInventory)>0.0001)failures.push({reportKey:'sales-receipt-reconciliation',key:`SalesReceipt:${sourceId}:inventory`,label:`Sales Receipt ${sourceId} inventory`,metric:'quantity',quickBooksValue:expectedInventory,hisabValue:actualInventory,difference:actualInventory-expectedInventory,materiality:0,severity:'ERROR',recommendedAction:'Re-run idempotent Sales Receipt inventory and COGS materialization.',sourceRefs:[{sourceId,documentId:String(receipt.id)}]})
      for(const movement of receiptMovements){const costing=ledgerByMovement.get(String(movement.id))??[],costDebit=costing.reduce((sum,item)=>sum+number(item.debit),0),costCredit=costing.reduce((sum,item)=>sum+number(item.credit),0);if(costing.length<2||Math.abs(costDebit-costCredit)>0.0001)failures.push({reportKey:'sales-receipt-reconciliation',key:`SalesReceipt:${sourceId}:cogs:${movement.id}`,label:`Sales Receipt ${sourceId} COGS`,metric:'cogsPosting',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:'Regenerate the balanced COGS and inventory-asset journal for this stock movement.',sourceRefs:[{sourceId,documentId:String(receipt.id)}]})}
      if(String(receipt.source_deposit_account_id??'')!==String(object(raw.DepositToAccountRef).value??'')||String(receipt.source_payment_method_id??'')!==String(object(raw.PaymentMethodRef).value??''))failures.push({reportKey:'sales-receipt-reconciliation',key:`SalesReceipt:${sourceId}:payment`,label:`Sales Receipt ${sourceId} payment`,metric:'sourceRelationships',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:'Re-import the exact deposit-account and payment-method references.',sourceRefs:[{sourceId,documentId:String(receipt.id)}]})
      for(const [index,line] of localLines.entries())local.push({key:`SalesReceipt:${sourceId}:line:${index}`,label:`Sales Receipt ${sourceId} line ${index+1}`,currency:String(receipt.currency),localId:String(line.id),values:{amount:number(line.amount),quantity:number(line.quantity)}})
      for(const [index,line] of sourceLines.entries()){const detail=object(line.SalesItemLineDetail),actual=localLines[index];source.push({key:`SalesReceipt:${sourceId}:line:${index}`,label:`Sales Receipt ${sourceId} line ${index+1}`,currency,sourceId,values:{amount:number(line.Amount),quantity:number(detail.Qty??1)}});if(actual&&(String(actual.source_item_id??'')!==String(object(detail.ItemRef).value??'')||String(actual.source_class_id??'')!==String(object(detail.ClassRef).value??'')||String(actual.source_tax_code_id??'')!==String(object(detail.TaxCodeRef).value??'')))failures.push({reportKey:'sales-receipt-reconciliation',key:`SalesReceipt:${sourceId}:line:${index}:relationships`,label:`Sales Receipt ${sourceId} line ${index+1}`,metric:'sourceRelationships',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:'Re-import the exact item, class, and tax-code line references.',sourceRefs:[{sourceId,documentId:String(actual.id)}]})}
    }
  }
  const section=compareFxRows('sales-receipt-reconciliation','Sales Receipts, deposits, revenue, tax, inventory, and COGS',source,local,parameters);section.differences.push(...failures);if(failures.length)section.status='FAILED';section.comparedRows+=failures.length;section.maximumDifference=section.differences.reduce((max,item)=>Math.max(max,Math.abs(item.difference)),section.maximumDifference);return section
}
