import 'server-only'
import { createAdminClient } from '@/lib/supabase/admin'
import { extractQuickBooksPaymentRelationships } from '@/lib/import-export/quickbooks/payment-relationships'
import { compareFxRows,type FxComparableRow } from './multicurrency-engine'
import type { CertificationDifference,CertificationParameters,CertificationSection } from './types'

type Row=Record<string,unknown>
const object=(value:unknown):Row=>value&&typeof value==='object'?value as Row:{}
const number=(value:unknown)=>Number.isFinite(Number(value))?Number(value):0
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function pages(table:string,build:(query:any)=>any){const db=createAdminClient(),rows:Row[]=[];for(let from=0;;from+=1000){const result=await build(db.from(table).select('*')).range(from,from+999);if(result.error)throw result.error;rows.push(...((result.data??[]) as Row[]));if((result.data?.length??0)<1000)break}return rows}

export async function certifyVendorCredits(companyId:string,realmId:string,parameters:CertificationParameters):Promise<CertificationSection>{
  const [records,billPayments,credits,lines,applications,ledger,movements]=await Promise.all([
    pages('quickbooks_migration_records',q=>q.eq('company_id',companyId).eq('realm_id',realmId).eq('entity_type','VendorCredit').eq('is_deleted',false)),pages('quickbooks_migration_records',q=>q.eq('company_id',companyId).eq('realm_id',realmId).eq('entity_type','BillPayment').eq('is_deleted',false)),pages('vendor_credits',q=>q.eq('company_id',companyId).is('deleted_at',null)),pages('vendor_credit_lines',q=>q.eq('company_id',companyId)),pages('vendor_credit_applications',q=>q.eq('company_id',companyId)),pages('ledger_entries',q=>q.eq('company_id',companyId).eq('source_type','SUPPLIER_CREDIT')),pages('stock_movements',q=>q.eq('company_id',companyId).eq('source_type','SUPPLIER_CREDIT')),
  ])
  const source:FxComparableRow[]=[],local:FxComparableRow[]=[],failures:CertificationDifference[]=[],creditBySource=new Map(credits.map(item=>[String(item.legacy_id),item])),linesByCredit=new Map<string,Row[]>(),appsByCredit=new Map<string,Row[]>(),ledgerByCredit=new Map<string,Row[]>(),movesByCredit=new Map<string,Row[]>()
  for(const item of lines){const key=String(item.vendor_credit_id),list=linesByCredit.get(key)??[];list.push(item);linesByCredit.set(key,list)}for(const item of applications){const key=String(item.vendor_credit_id),list=appsByCredit.get(key)??[];list.push(item);appsByCredit.set(key,list)}for(const item of ledger){const key=String(item.source_id),list=ledgerByCredit.get(key)??[];list.push(item);ledgerByCredit.set(key,list)}for(const item of movements){const key=String(item.source_id),list=movesByCredit.get(key)??[];list.push(item);movesByCredit.set(key,list)}
  const expectedApplications=new Map<string,Array<{key:string;amount:number;billId:string;paymentId:string}>>()
  for(const payment of billPayments){const paymentId=String(payment.source_id),relationships=extractQuickBooksPaymentRelationships(object(payment.source_payload),'VENDOR');for(const allocation of relationships.allocations){if(allocation.creditAmount<=0)continue;if(allocation.creditSourceIds.length!==1){failures.push({reportKey:'vendor-credit-reconciliation',key:`BillPayment:${paymentId}:${allocation.sourceLineKey}`,label:`BillPayment ${paymentId}`,metric:'creditEvidence',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:'QuickBooks does not identify exactly one Vendor Credit for this bill application.',sourceRefs:[{sourceId:paymentId}]});continue}const creditId=allocation.creditSourceIds[0],list=expectedApplications.get(creditId)??[];list.push({key:`VendorCredit:${creditId}:application:${paymentId}:${allocation.sourceLineKey}:${allocation.targetSourceId}`,amount:allocation.creditAmount,billId:allocation.targetSourceId,paymentId});expectedApplications.set(creditId,list)}}
  for(const record of records){const sourceId=String(record.source_id),raw=object(record.source_payload),sourceLines=(Array.isArray(raw.Line)?raw.Line:[]).map(object),credit=creditBySource.get(sourceId),currency=String(record.currency_code??parameters.homeCurrency).toUpperCase(),expectedApps=expectedApplications.get(sourceId)??[],sourceBalance=raw.Balance===undefined?number(raw.TotalAmt)-expectedApps.reduce((sum,item)=>sum+item.amount,0):number(raw.Balance)
    source.push({key:`VendorCredit:${sourceId}:summary`,label:`Vendor Credit ${sourceId}`,currency,sourceId,values:{total:number(raw.TotalAmt),tax:number(object(raw.TxnTaxDetail).TotalTax),applied:number(raw.TotalAmt)-sourceBalance,balance:sourceBalance,lines:sourceLines.length}})
    if(credit){const localLines=linesByCredit.get(String(credit.id))??[],localApps=appsByCredit.get(String(credit.id))??[];local.push({key:`VendorCredit:${sourceId}:summary`,label:`Vendor Credit ${sourceId}`,currency:String(credit.currency),localId:String(credit.id),values:{total:number(credit.total),tax:number(credit.tax_amount),applied:number(credit.applied_amount),balance:number(credit.balance),lines:localLines.length}});for(const [index,line] of localLines.sort((a,b)=>number(a.line_no)-number(b.line_no)).entries())local.push({key:`VendorCredit:${sourceId}:line:${index}`,label:`Vendor Credit ${sourceId} line ${index+1}`,currency:String(credit.currency),localId:String(line.id),values:{amount:number(line.amount),quantity:number(line.quantity)}});for(const application of localApps)local.push({key:`VendorCredit:${sourceId}:application:${application.source_bill_payment_id}:${application.source_line_key}:${application.source_bill_id}`,label:`Vendor Credit ${sourceId} application`,currency:String(application.currency),localId:String(application.id),values:{amount:number(application.amount)}})
      const ledgerLines=ledgerByCredit.get(String(credit.id))??[],debit=ledgerLines.reduce((sum,item)=>sum+number(item.debit),0),ledgerCredit=ledgerLines.reduce((sum,item)=>sum+number(item.credit),0),apDebit=ledgerLines.filter(item=>String(item.account_id)===String(credit.ap_account_id)).reduce((sum,item)=>sum+number(item.debit),0);if(Math.abs(debit-ledgerCredit)>0.0001||Math.abs(apDebit-number(credit.total))>0.0001)failures.push({reportKey:'vendor-credit-reconciliation',key:`VendorCredit:${sourceId}:ledger`,label:`Vendor Credit ${sourceId} ledger`,metric:'apReduction',quickBooksValue:number(credit.total),hisabValue:apDebit,difference:apDebit-number(credit.total),materiality:parameters.absoluteTolerance,severity:'ERROR',recommendedAction:`Regenerate the Vendor Credit ledger; debit ${debit.toFixed(4)}, credit ${ledgerCredit.toFixed(4)}.`,sourceRefs:[{sourceId,documentId:String(credit.id)}]})
      const expectedInventory=localLines.filter(item=>item.inventory_item_id).reduce((sum,item)=>sum+number(item.quantity),0),actualInventory=Math.abs((movesByCredit.get(String(credit.id))??[]).reduce((sum,item)=>sum+number(item.quantity),0));if(Math.abs(expectedInventory-actualInventory)>0.0001)failures.push({reportKey:'vendor-credit-reconciliation',key:`VendorCredit:${sourceId}:inventory`,label:`Vendor Credit ${sourceId} inventory return`,metric:'quantity',quickBooksValue:expectedInventory,hisabValue:actualInventory,difference:actualInventory-expectedInventory,materiality:0,severity:'ERROR',recommendedAction:'Re-run the idempotent supplier-return inventory materialization.',sourceRefs:[{sourceId,documentId:String(credit.id)}]})
    }
    for(const [index,line] of sourceLines.entries()){const detail=object(line.ItemBasedExpenseLineDetail??line.AccountBasedExpenseLineDetail),actual=credit?(linesByCredit.get(String(credit.id))??[]).find(item=>number(item.line_no)===index+1):undefined,expectedItem=String(object(detail.ItemRef).value??''),expectedAccount=String(object(detail.AccountRef).value??''),expectedClass=String(object(detail.ClassRef).value??''),expectedTax=String(object(detail.TaxCodeRef).value??'');source.push({key:`VendorCredit:${sourceId}:line:${index}`,label:`Vendor Credit ${sourceId} line ${index+1}`,currency,sourceId,values:{amount:number(line.Amount),quantity:number(detail.Qty??1)}});if(actual&&(String(actual.source_item_id??'')!==expectedItem||String(actual.source_account_id??'')!==expectedAccount||String(actual.source_class_id??'')!==expectedClass||String(actual.source_tax_code_id??'')!==expectedTax))failures.push({reportKey:'vendor-credit-reconciliation',key:`VendorCredit:${sourceId}:line:${index}:relationships`,label:`Vendor Credit ${sourceId} line ${index+1}`,metric:'sourceRelationships',quickBooksValue:1,hisabValue:0,difference:-1,materiality:0,severity:'ERROR',recommendedAction:'Re-import the line with its exact item, account, class, and tax-code references.',sourceRefs:[{sourceId,documentId:String(actual.id)}]})}
    for(const application of expectedApps)source.push({key:application.key,label:`Vendor Credit ${sourceId} application`,currency,sourceId,values:{amount:application.amount}})
  }
  const section=compareFxRows('vendor-credit-reconciliation','Vendor Credits, AP, applications, tax, and inventory',source,local,parameters);section.differences.push(...failures);if(failures.length)section.status='FAILED';section.comparedRows+=failures.length;section.maximumDifference=section.differences.reduce((max,item)=>Math.max(max,Math.abs(item.difference)),section.maximumDifference);return section
}
