import type { Metadata } from 'next'
import { LegalCallout, LegalPage, type LegalSection } from '@/components/legal/LegalPage'
import { getLegalMetadataBase, legalConfig } from '@/lib/legal-config'

export const metadata: Metadata = {
  metadataBase: getLegalMetadataBase(),
  title: 'Hisab AI Terms of Service',
  description: 'Terms of Service and End-User License Agreement for hisab.ai.',
  alternates: { canonical: '/terms' },
}

const sections: LegalSection[] = [
  { id: 'introduction', title: 'Introduction', children: <p>These Terms of Service and End-User License Agreement govern access to and use of {legalConfig.productName}, an accounting and business-management SaaS platform operated by {legalConfig.legalEntityName} (collectively, “Hisab AI,” “we,” or “us”).</p> },
  { id: 'acceptance', title: 'Acceptance of Terms', children: <p>By creating an account, accessing the service, or using any integration, you agree to these Terms. If you use the service for an organization, you represent that you have authority to bind that organization, which is the “Customer.”</p> },
  { id: 'description', title: 'Description of Hisab AI', children: <p>Hisab AI provides tools for bookkeeping, accounting operations, financial records, reporting, document workflows, business data management, AI-assisted features, imports, and integrations. Features may vary by plan, configuration, region, and availability.</p> },
  { id: 'accounts', title: 'User Accounts', children: <p>You must provide accurate account information, keep credentials confidential, and promptly notify us of suspected unauthorized access. You are responsible for activity performed through your account and for maintaining appropriate user permissions within your organization.</p> },
  { id: 'responsibilities', title: 'Customer Responsibilities', children: <p>You are responsible for your instructions, users, source data, permissions, configuration, review of outputs, and compliance with laws applicable to your business. You must not use the service to process data you are not authorized to provide.</p> },
  { id: 'acceptable-use', title: 'Acceptable Use', children: <><p>You may not misuse the service, interfere with its operation, bypass access controls, probe or attack systems, upload malicious code, infringe rights, use it for unlawful activity, or attempt to access another customer’s data.</p></> },
  { id: 'accounting-information', title: 'Accounting and Financial Information', children: <p>Hisab AI is a software tool. You remain responsible for accounting judgments, entries, classifications, reconciliations, reports, filings, and decisions made using the service.</p> },
  { id: 'quickbooks', title: 'QuickBooks / Intuit Integration', children: <><p>Hisab AI may integrate with QuickBooks Online through Intuit APIs. You initiate the connection and must have authorization to connect and provide access to the QuickBooks company. Hisab AI accesses authorized data only after that connection is approved and does not obtain or store your QuickBooks password.</p><p>Depending on the selected functionality, Hisab AI may retrieve accounting data needed for migration, import, validation, mapping, reconciliation, or synchronization. OAuth credentials and tokens are handled by the application’s server-side integration services and are not intended to be exposed in frontend code. You can disconnect the integration using available controls. Intuit and other third-party services remain subject to their own terms and policies. Hisab AI does not claim ownership of your QuickBooks accounting data.</p></> },
  { id: 'third-party-services', title: 'Third-Party Services', children: <p>Third-party services, including QuickBooks Online and Intuit APIs, are controlled by their providers. We are not responsible for third-party availability, changes, errors, policies, or content. Your use of those services is governed by your agreements with their providers.</p> },
  { id: 'migration', title: 'Data Import and Migration', children: <><p>The migration process may retrieve records from QuickBooks Online, transform them into Hisab AI’s data model, and import supported records including customers, vendors or suppliers, products or items, chart of accounts, invoices, bills, payments, credit notes or credits where supported, journal entries where supported, and other supported accounting records.</p><p>Results depend on source-system data quality, supported entities, API availability, mappings, user permissions, third-party limitations, and validation results. You must review migrated data before relying on it for accounting, tax, reporting, or regulatory purposes. No promise of complete or error-free migration is made.</p></> },
  { id: 'customer-data', title: 'User Content and Customer Data', children: <p>You retain ownership of data and content you submit (“Customer Data”). You grant Hisab AI the limited rights needed to host, process, transmit, transform, display, back up, and otherwise use Customer Data to provide, secure, maintain, and improve the service as permitted by these Terms and your instructions.</p> },
  { id: 'ip', title: 'Intellectual Property', children: <p>Hisab AI and its software, interfaces, documentation, branding, and underlying technology are owned by or licensed to Hisab AI and are protected by applicable intellectual-property laws. These Terms do not transfer ownership to you.</p> },
  { id: 'license', title: 'Software License', children: <p>Subject to these Terms, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the service for your internal business purposes during the applicable subscription or account period.</p> },
  { id: 'ai', title: 'AI-Generated Information and Limitations', children: <><p>AI-assisted features may generate suggestions, summaries, classifications, or other outputs that contain errors, omissions, or inappropriate conclusions. Review outputs before relying on them.</p><p>AI does not replace a qualified accountant, tax advisor, lawyer, auditor, or other professional. You remain responsible for financial decisions, filings, and verification of important accounting and tax information.</p></> },
  { id: 'tax-disclaimer', title: 'Accounting and Tax Disclaimer', children: <LegalCallout>Hisab AI does not provide accounting, tax, legal, audit, or other professional advice. Consult a qualified professional for advice specific to your circumstances.</LegalCallout> },
  { id: 'accuracy', title: 'Data Accuracy', children: <p>You are responsible for the completeness, legality, and accuracy of Customer Data and for checking calculations, mappings, imported records, reports, and other results.</p> },
  { id: 'availability', title: 'Service Availability', children: <p>We aim to provide a reliable service but do not guarantee uninterrupted, timely, or error-free availability. Maintenance, updates, provider outages, network conditions, and events beyond our reasonable control may affect access.</p> },
  { id: 'security', title: 'Security', children: <p>We use technical and organizational measures appropriate to the service, including authenticated access controls, tenant-scoped authorization, server-side handling of integrations, audit records for relevant operations, and encrypted storage of integration tokens. No method of transmission or storage is completely secure.</p> },
  { id: 'fees', title: 'Fees and Payments', children: <p>Any fees, usage limits, trials, or payment terms presented in an order, plan, or other service-specific agreement apply to that use. If no fees are presented, no paid commitment is created by these Terms alone.</p> },
  { id: 'suspension', title: 'Suspension and Termination', children: <p>You may stop using the service at any time. We may suspend or terminate access for material breach, security risk, unlawful use, non-payment where applicable, or to protect the service and users. Provisions that by their nature should survive termination will survive.</p> },
  { id: 'deletion', title: 'Data Deletion', children: <p>After account closure or a valid deletion request, we will handle Customer Data in accordance with our Privacy Policy and applicable service records. Contact {legalConfig.contactEmail} to request deletion or ask about available account controls.</p> },
  { id: 'links', title: 'Third-Party Links and Services', children: <p>The service may reference third-party websites or services. Links are provided for convenience and do not constitute endorsement. Review third-party terms before using them.</p> },
  { id: 'liability', title: 'Limitation of Liability', children: <p>To the maximum extent permitted by applicable law, Hisab AI and its personnel will not be liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or for loss of profits, revenue, goodwill, business opportunities, or data, arising from or related to the service. Any applicable liability cap must be confirmed in a signed or service-specific agreement; where none applies, liability is limited to the maximum extent permitted by law.</p> },
  { id: 'indemnification', title: 'Indemnification', children: <p>You agree to defend, indemnify, and hold harmless Hisab AI and its personnel from claims, losses, liabilities, and expenses arising from your unlawful use of the service, breach of these Terms, violation of another party’s rights, or Customer Data and instructions.</p> },
  { id: 'warranties', title: 'Disclaimer of Warranties', children: <p>To the maximum extent permitted by law, the service is provided “as is” and “as available,” without warranties of any kind, whether express, implied, or statutory, including accuracy, fitness for a particular purpose, non-infringement, or uninterrupted availability.</p> },
  { id: 'service-changes', title: 'Changes to the Service', children: <p>We may modify, suspend, or discontinue features, integrations, or parts of the service. We will use reasonable efforts to communicate material changes through the service or other available channels.</p> },
  { id: 'terms-changes', title: 'Changes to These Terms', children: <p>We may update these Terms from time to time. The revised version will be posted at this URL with an updated date. Continued use after the effective date of a revision constitutes acceptance to the extent permitted by law.</p> },
  { id: 'governing-law', title: 'Governing Law / Dispute Resolution', children: <p>These Terms are governed by the laws of {legalConfig.governingLaw}. Any disputes will be resolved in or under the jurisdiction of {legalConfig.jurisdiction}, subject to any mandatory rights under applicable law.</p> },
]

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of Service" description="These Terms also serve as the End-User License Agreement for hisab.ai and describe the rules that apply when you use our accounting and business-management platform." sections={sections} />
}
