import type { Metadata } from 'next'
import { LegalCallout, LegalList, LegalPage, type LegalSection } from '@/components/legal/LegalPage'
import { getLegalMetadataBase, legalConfig } from '@/lib/legal-config'

export const metadata: Metadata = {
  metadataBase: getLegalMetadataBase(),
  title: 'Hisab AI Privacy Policy',
  description: 'Privacy Policy for hisab.ai.',
  alternates: { canonical: '/privacy' },
}

const sections: LegalSection[] = [
  { id: 'introduction', title: 'Introduction', children: <p>This Privacy Policy explains how {legalConfig.legalEntityName} (“Hisab AI,” “we,” or “us”) collects, uses, stores, shares, and protects information when you use {legalConfig.productName}.</p> },
  { id: 'collect', title: 'Information We Collect', children: <p>We collect information you provide, information generated through use of the service, and information received from integrations you authorize. We collect only what is reasonably needed to operate and secure the service.</p> },
  { id: 'provided', title: 'Information Provided by Users', children: <p>This may include names, email addresses, account credentials handled by our authentication provider, company and profile details, accounting records, documents, configuration, support requests, and other content you choose to submit.</p> },
  { id: 'account', title: 'Account Information', children: <p>We use account and profile information to authenticate users, associate users with authorized companies, provide access, communicate about the service, and protect accounts.</p> },
  { id: 'business-data', title: 'Business and Accounting Data', children: <p>Depending on the features you use, Hisab AI processes business, accounting, transaction, customer, vendor, employee, product, tax, payroll, banking, document, and reporting data submitted or generated within your company workspace.</p> },
  { id: 'quickbooks-data', title: 'QuickBooks Online and Intuit Data', children: <><p>When you connect QuickBooks Online to Hisab AI, we may receive accounting and business information from the connected QuickBooks company, depending on the permissions and API functionality authorized by you. Examples may include company information; customers; vendors; employees where authorized and supported; products or items; chart of accounts; invoices; bills; payments; credit transactions; journal entries; tax and accounting information; and other supported accounting records.</p><p>We use this information to provide requested accounting data migration, data import, validation, mapping, reconciliation, synchronization if enabled, and accounting or business-management functionality. Hisab AI does not claim ownership of your QuickBooks data.</p></> },
  { id: 'automatic', title: 'Information Collected Automatically', children: <p>Our infrastructure and authentication services may receive technical information such as IP address, browser or device characteristics, request timestamps, error information, and security or audit events needed to operate and protect the service.</p> },
  { id: 'cookies', title: 'Cookies and Similar Technologies', children: <p>Hisab AI uses authentication and session cookies required to keep users signed in and maintain secure requests. The current application does not include a separate marketing or analytics-cookie system in its application code. Third-party providers may set or process cookies under their own policies when you use their services.</p> },
  { id: 'use', title: 'How We Use Information', children: <LegalList><li>Provide, operate, maintain, and secure the service.</li><li>Authenticate users and enforce company and role access.</li><li>Process imports, migrations, validations, reports, and integrations requested by you.</li><li>Respond to support requests and communicate service information.</li><li>Detect, prevent, investigate, and address fraud, abuse, errors, and security incidents.</li><li>Comply with legal obligations and enforce our agreements.</li></LegalList> },
  { id: 'qb-integration', title: 'QuickBooks Integration', children: <><p>You initiate the QuickBooks connection, authenticate with Intuit or QuickBooks, and authorize Hisab AI. The OAuth process provides authorization credentials or tokens that Hisab AI uses to access the authorized QuickBooks company. Hisab AI does not require your QuickBooks password.</p><p>You may disconnect or revoke the integration through available controls. When disconnected, the application clears local connection credentials; remote revocation may depend on the provider being available. QuickBooks Online and Intuit remain separate services subject to their own terms and policies.</p></> },
  { id: 'ai-processing', title: 'AI Processing', children: <p>When you use AI-assisted functionality, relevant prompts, records, or outputs may be processed to provide that feature. The application code reviewed does not identify a configured external AI provider or AI API call, so no external AI processing or model-training practice is represented here. If an external AI provider is introduced, this policy should be updated before that feature is used with Customer Data. Review your organization’s permissions and instructions before submitting sensitive information. AI outputs may be inaccurate and are not professional advice.</p> },
  { id: 'storage', title: 'Data Storage', children: <p>Hisab AI’s primary production database is hosted in the {legalConfig.primaryDataRegion} region (AWS region <code>ap-southeast-2</code>). The application also uses Supabase Authentication and Supabase Storage, including storage for company files and QuickBooks migration attachments. The repository does not establish that every store, log, worker, or provider-managed service uses the same region. Integration processing and background migration jobs may create staging, checkpoint, audit, report, or attachment records needed to complete and explain requested work.</p> },
  { id: 'security', title: 'Data Security', children: <p>We use authenticated access, tenant-scoped authorization, server-side integration processing, audit records for relevant operations, and encryption for stored QuickBooks integration tokens. We do not claim that any security measure makes data absolutely secure, and we do not claim SOC 2, ISO, GDPR, HIPAA, PCI, or other certification unless separately stated in a verified agreement.</p> },
  { id: 'retention', title: 'Data Retention', children: <LegalCallout>TechDotGlobal’s policy is to delete customer data after three months. Repository review did not identify a single system-wide automated workflow that enforces deletion of every database record, uploaded file, migration record, audit record, log, worker record, or provider-managed backup at that point. Until that enforcement is completed and verified, deletion timing may depend on the relevant application control, service provider, legal obligation, or record type. Provider-managed backup retention remains subject to provider infrastructure settings that are not verified in this repository.</LegalCallout> },
  { id: 'deletion', title: 'Data Deletion', children: <p>You may request deletion of account and Customer Data by contacting {legalConfig.privacyEmail}. We may need to verify the request and may retain limited information where required for security, legal obligations, dispute resolution, or legitimate records. Account and integration deletion behavior is subject to the available application controls and provider limitations.</p> },
  { id: 'sharing', title: 'Data Sharing', children: <p>We may share information with service providers that process it for hosting, authentication, storage, infrastructure, support, security, or other services on our behalf; with integrations you explicitly connect; when required by law; or as necessary to protect rights, safety, and the service. We do not sell Customer Data.</p> },
  { id: 'providers', title: 'Service Providers', children: <p>Service providers may process information only as needed to provide contracted services. The application currently relies on Supabase for authentication, database, and storage capabilities and on Intuit APIs when you authorize QuickBooks integration. Provider practices are governed by their own terms and privacy policies.</p> },
  { id: 'third-party', title: 'Third-Party Integrations', children: <p>If you connect a third-party service, you direct us to exchange information with that service. We are not responsible for third-party privacy practices, availability, or controls. Review the third party’s privacy notice before connecting it.</p> },
  { id: 'transfers', title: 'International Data Transfers', children: <p>Because the primary production database is hosted in Sydney, Australia, customer information may be stored and processed in Australia and may be processed in other jurisdictions by service providers used to operate the service. TechDotGlobal takes reasonable measures to protect customer information when it is processed internationally, but does not claim a specific transfer mechanism or certification unless separately confirmed.</p> },
  { id: 'rights', title: 'User Rights', children: <p>Depending on your location and applicable law, you may have rights to access, correct, delete, restrict, object to, or receive a copy of personal information. Contact {legalConfig.privacyEmail} to make a request. We may verify identity and apply legally permitted exceptions.</p> },
  { id: 'closure', title: 'Account Closure', children: <p>You may close your account using available controls or by contacting {legalConfig.supportEmail}. Closing an account may stop access and begin deletion workflows, but some information may remain for the purposes described in “Data Retention.”</p> },
  { id: 'children', title: 'Children’s Privacy', children: <p>The service is intended for businesses and is not directed to children. We do not knowingly request personal information from children in violation of applicable law.</p> },
  { id: 'marketing', title: 'Marketing Communications', children: <p>We may send service-related communications needed to administer your account. Marketing communications, if introduced, will include an available unsubscribe mechanism where required. The current application contains no separate marketing-analytics system.</p> },
  { id: 'changes', title: 'Changes to This Privacy Policy', children: <p>We may update this Privacy Policy as the service or legal requirements change. We will post the updated version at this URL and revise the “Last updated” date. Continued use after an update means the revised policy applies to the extent permitted by law.</p> },
  { id: 'contact', title: 'Contact Information', children: <p>For privacy questions or data requests, contact {legalConfig.privacyEmail}. For general support, contact {legalConfig.supportEmail}. The responsible legal entity is {legalConfig.legalEntityName}; its address is {legalConfig.businessAddress}.</p> },
]

export default function PrivacyPage() {
  return <LegalPage eyebrow="Legal" title="Privacy Policy" description="This Privacy Policy explains how hisab.ai handles information when you use our accounting, business-management, AI-assisted, and QuickBooks integration features." sections={sections} />
}
