import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import * as XLSX from 'xlsx'
import {
  buildClassTemplateSheet,
  buildLocationTemplateSheet,
  buildProjectTemplateSheet,
  parseProjectProductServiceSheet,
  parseVerticalListSheet,
} from '../../src/lib/cost-centers/import/parsers'
import {
  normalizeCostCenterNameKey,
  PROJECT_PRODUCT_SERVICE_HEADERS,
  slugifyCostCenterCode,
} from '../../src/lib/cost-centers/import/constants'
import { isExcelFooterOrMetadata } from '../../src/lib/cost-centers/import/footer-metadata'

function aoaToBuffer(rows: (string | number)[][]): ArrayBuffer {
  const sheet = XLSX.utils.aoa_to_sheet(rows)
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, sheet, 'Sheet1')
  return XLSX.write(workbook, { type: 'array', bookType: 'xlsx' }) as ArrayBuffer
}

describe('excel footer metadata detection', () => {
  it('detects common print timestamps and footer text', () => {
    assert.equal(isExcelFooterOrMetadata('Thursday, July 02, 2026 02:47 PM GMTZ'), true)
    assert.equal(isExcelFooterOrMetadata('Thursday, July 02, 2026 02:41 PM GMTZ'), true)
    assert.equal(isExcelFooterOrMetadata('Printed on 07/02/2026'), true)
    assert.equal(isExcelFooterOrMetadata('Generated by Microsoft Excel'), true)
    assert.equal(isExcelFooterOrMetadata('Page 1 of 1'), true)
    assert.equal(isExcelFooterOrMetadata('2026-07-02T14:47:00Z'), true)
    assert.equal(isExcelFooterOrMetadata(new Date('2026-07-02T14:47:00Z')), true)
    assert.equal(isExcelFooterOrMetadata('Wadi Dawasir'), false)
    assert.equal(isExcelFooterOrMetadata('WEST'), false)
    assert.equal(isExcelFooterOrMetadata('ADMINISTRATION:Office Expense'), false)
    assert.equal(isExcelFooterOrMetadata('CIVIL WORKS:Office Expense'), false)
  })
})

describe('class name uniqueness / code generation', () => {
  it('treats only the complete name as the duplicate key', () => {
    assert.equal(normalizeCostCenterNameKey('ADMINISTRATION'), 'administration')
    assert.notEqual(
      normalizeCostCenterNameKey('ADMINISTRATION'),
      normalizeCostCenterNameKey('ADMINISTRATION:Office Expense'),
    )
    assert.notEqual(
      normalizeCostCenterNameKey('CIVIL WORKS:C2537'),
      normalizeCostCenterNameKey('CIVIL WORKS:C3742'),
    )
    assert.notEqual(
      normalizeCostCenterNameKey('MW/WL:Tiger Project:Tiger Team A'),
      normalizeCostCenterNameKey('MW/WL:Tiger Project:Tiger Team B'),
    )
  })

  it('generates distinct codes for classes that share a long parent path', () => {
    const a = slugifyCostCenterCode('MW/WL:Tiger Project:Tiger Team A', 'CLS')
    const b = slugifyCostCenterCode('MW/WL:Tiger Project:Tiger Team B', 'CLS')
    const c = slugifyCostCenterCode('MW/WL:Tiger Project:Tiger Team C', 'CLS')
    assert.notEqual(a, b)
    assert.notEqual(b, c)
    assert.notEqual(a, c)
    assert.ok(a.startsWith('CLS-'))
    assert.ok(a.includes('MW-WL-TIGER-PROJECT'))
  })

  it('generates distinct codes for parent vs parent:child', () => {
    const parent = slugifyCostCenterCode('ADMINISTRATION', 'CLS')
    const child = slugifyCostCenterCode('ADMINISTRATION:Office Expense', 'CLS')
    assert.notEqual(parent, child)
  })

  it('preserves full hierarchical class names when parsing', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Class List'],
      ['Class full name'],
      ['MW/WL:Tiger Project:Tiger Team A'],
      ['MW/WL:Tiger Project:Tiger Team B'],
      ['MW/WL:Tiger Project:Tiger Team C'],
    ])
    const result = parseVerticalListSheet(buffer, 'class')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      [
        'MW/WL:Tiger Project:Tiger Team A',
        'MW/WL:Tiger Project:Tiger Team B',
        'MW/WL:Tiger Project:Tiger Team C',
      ],
    )
    const codes = result.rows.map((r) => slugifyCostCenterCode(r.name, 'CLS'))
    assert.equal(new Set(codes).size, 3)
  })
})

describe('location vertical import parser', () => {
  it('skips company header, list title, column header and imports names', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Location List'],
      ['Location full name'],
      ['Afif'],
      ['Dammam'],
      [''],
      ['East Region'],
    ])
    const result = parseVerticalListSheet(buffer, 'location')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      ['Afif', 'Dammam', 'East Region'],
    )
    assert.equal(result.skippedEmpty, 1)
  })

  it('ignores excel footer timestamp after location list', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Location List'],
      ['Location full name'],
      ['Afif'],
      ['Dammam'],
      ['East Region'],
      ['Hafuf'],
      ['Wadi Dawasir'],
      ['WEST'],
      [''],
      ['Thursday, July 02, 2026 02:47 PM GMTZ'],
    ])
    const result = parseVerticalListSheet(buffer, 'location')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      ['Afif', 'Dammam', 'East Region', 'Hafuf', 'Wadi Dawasir', 'WEST'],
    )
    assert.ok(!result.rows.some((r) => /thursday|gmtz|2026/i.test(r.name)))
  })

  it('builds a downloadable location template that parses back', () => {
    const buffer = buildLocationTemplateSheet('ACME COMPANY')
    const result = parseVerticalListSheet(buffer, 'location')
    assert.ok(result.rows.length >= 1)
    assert.ok(result.rows.every((r) => !/company|location list|location full name/i.test(r.name)))
  })
})

describe('class vertical import parser', () => {
  it('preserves Parent:Child text and skips headers', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Class List'],
      ['Class full name'],
      ['ADMINISTRATION'],
      ['ADMINISTRATION:Office Expense'],
      ['BAHRAIN FO'],
    ])
    const result = parseVerticalListSheet(buffer, 'class')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      ['ADMINISTRATION', 'ADMINISTRATION:Office Expense', 'BAHRAIN FO'],
    )
  })

  it('ignores excel footer after class list', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Class List'],
      ['Class full name'],
      ['ADMINISTRATION'],
      ['CIVIL WORKS:C2537'],
      ['Printed on 07/02/2026'],
    ])
    const result = parseVerticalListSheet(buffer, 'class')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      ['ADMINISTRATION', 'CIVIL WORKS:C2537'],
    )
  })

  it('ignores exact Excel print footer timestamp that was wrongly imported as a Class', () => {
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      ['Class List'],
      ['Class full name'],
      ['ADMINISTRATION'],
      ['ADMINISTRATION:Office Expense'],
      ['CIVIL WORKS'],
      ['CIVIL WORKS:Office Expense'],
      [''],
      ['Thursday, July 02, 2026 02:41 PM GMTZ'],
    ])
    const result = parseVerticalListSheet(buffer, 'class')
    assert.deepEqual(
      result.rows.map((r) => r.name),
      [
        'ADMINISTRATION',
        'ADMINISTRATION:Office Expense',
        'CIVIL WORKS',
        'CIVIL WORKS:Office Expense',
      ],
    )
    assert.ok(!result.rows.some((r) => /thursday|july|gmtz|2026|printed|page/i.test(r.name)))
  })

  it('builds a class template that parses back', () => {
    const buffer = buildClassTemplateSheet()
    const result = parseVerticalListSheet(buffer, 'class')
    assert.ok(result.rows.some((r) => r.name.includes(':')))
  })
})

describe('project product/service import parser', () => {
  it('imports all columns and requires product/service name', () => {
    const headers = [...PROJECT_PRODUCT_SERVICE_HEADERS]
    const buffer = aoaToBuffer([
      ['NETKOM COMPANY FOR COMMUNICATION'],
      headers,
      [
        '12PCS SPANNER SET',
        '10',
        'Inventory',
        'Tools',
        'SKU-001',
        'No',
        'Yes',
        '150',
        '100',
        '4100',
        '5000',
        '1500',
        'Spanners',
        'Buy spanners',
        '5',
        'Supplier A',
      ],
      ['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      [
        'ALLENKEY SET',
        '2',
        'Non-inventory',
        '',
        '',
        '',
        '',
        '80',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
      ],
    ])

    const result = parseProjectProductServiceSheet(buffer)
    assert.equal(result.rows.length, 2)
    assert.equal(result.rows[0].name, '12PCS SPANNER SET')
    assert.equal(result.rows[0].fields['SKU'], 'SKU-001')
    assert.equal(result.rows[0].fields['Price'], '150')
    assert.equal(result.rows[0].fields['Cost'], '100')
    assert.equal(result.rows[0].fields['Sales Description'], 'Spanners')
    assert.equal(result.rows[1].name, 'ALLENKEY SET')
    assert.ok(result.skippedEmpty >= 1)
  })

  it('ignores footer timestamp rows after product data', () => {
    const headers = [...PROJECT_PRODUCT_SERVICE_HEADERS]
    const buffer = aoaToBuffer([
      headers,
      ['12PCS SPANNER SET', '1', 'Inventory', '', '', '', '', '', '', '', '', '', '', '', '', ''],
      ['Thursday, July 02, 2026 02:47 PM GMTZ', '', '', '', '', '', '', '', '', '', '', '', '', '', '', ''],
    ])
    const result = parseProjectProductServiceSheet(buffer)
    assert.equal(result.rows.length, 1)
    assert.equal(result.rows[0].name, '12PCS SPANNER SET')
  })

  it('builds a project template with exact headers', () => {
    const buffer = buildProjectTemplateSheet()
    const result = parseProjectProductServiceSheet(buffer)
    assert.ok(result.headers.includes('Product/Service Name'))
    assert.ok(result.rows.length >= 1)
  })
})
