import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { generateEgsIdentity } from '../../src/lib/zatca/onboarding/egs-identity'
import { mapOnboardingError } from '../../src/lib/zatca/onboarding/onboarding-errors'
import { resolveOnboardingStatusAfterProductionFailure } from '../../src/lib/zatca/onboarding/onboarding-status'
import { verifyZatcaCsr } from '../../src/lib/zatca/onboarding/verify-csr'
import {
  isAlreadyConnected,
  resolveConnectionLabel,
  validateCompanyProfileForZatca,
  validateOnboardingState,
} from '../../src/lib/zatca/onboarding/validate-onboarding'

// A CSR in the exact shape the ZATCA gateway ACCEPTS (verified end-to-end against
// the developer-portal: UTF8String DN/SAN values + surname (2.5.4.4) for SN +
// PRINTABLESTRING certificateTemplateName). Generated by the production CSR builder.
const REAL_ACCEPTED_SANDBOX_CSR = `-----BEGIN CERTIFICATE REQUEST-----
MIICPjCCAeMCAQAwaTELMAkGA1UEBgwCU0ExETAPBgNVBAsMCEFsIE1hbHFhMSkw
JwYDVQQKDCBORVRLT00gQ09NUEFOWSBGT1IgQ09NTVVOSUNBVElPTjEcMBoGA1UE
AwwTVFNULTMxMTI3MTExMjkwMDAwMzBWMBAGByqGSM49AgEGBSuBBAAKA0IABAcu
aTA4XEHEtQ6//EjfQOKGtD32JnlavCzJ/8lGH1t2UoerZR/Fd2TbvEMmE9GlX1yE
yHBn7r99IwSAEdldPQWgggEZMIIBFQYJKoZIhvcNAQkOMYIBBjCCAQIwJAYJKwYB
BAGCNxQCBBcTFVBSRVpBVENBLUNvZGUtU2lnbmluZzCB2QYDVR0RBIHRMIHOpIHL
MIHIMUEwPwYDVQQEDDgxLWhpc2FiLmFpfDItaGlzYWIuYWl8My0xMzJiNGE3MGQw
NDhkZGNhZmRlMTRjYmY4NGQ1ZmM3YjEfMB0GCgmSJomT8ixkAQEMDzMxMTI3MTEx
MjkwMDAwMzENMAsGA1UEDAwEMTEwMDE2MDQGA1UEGgwtMzE0MSwgQW5hcyBCaW4g
TWFsaWssIEFsIE1hbHFhLCBSSVlBREgsIDEzNTIxMRswGQYDVQQPDBJUZWxlY29t
bXVuaWNhdGlvbnMwCgYIKoZIzj0EAwIDSQAwRgIhALBN4p4j/Kf8Ie2FfT2W9afi
bfz9+pmBAJZhurOVqgZSAiEAlb6Ht1p6ncBO3ZOdPxHJuQI27rkCAwGzYQAyj1TP
U0A=
-----END CERTIFICATE REQUEST-----`

const baseSettings = {
  companyName: 'NETKOM COMPANY',
  legalName: 'NETKOM COMPANY FOR COMMUNICATION',
  taxId: '300000000000003',
  commercialRegistration: '1010123456',
  zatcaEnvironment: 'SANDBOX' as const,
  city: 'Riyadh',
  buildingNumber: '1234',
  streetAddress: 'King Fahd Road',
  address: '',
  district: 'Al Olaya',
  postalCode: '12345',
}

describe('validateCompanyProfileForZatca', () => {
  it('passes with complete company data and OTP', () => {
    const result = validateCompanyProfileForZatca(baseSettings, { requireOtp: true, otp: '123456' })
    assert.equal(result.valid, true)
    assert.equal(result.errors.length, 0)
  })

  it('fails when VAT number is missing (case 4)', () => {
    const result = validateOnboardingState(
      { ...baseSettings, taxId: '123' },
      { requireOtp: true, otp: '123456' },
    )
    assert.equal(result.valid, false)
    assert.match(result.errors.join(' '), /15 digits/i)
  })

  it('fails when CR number is missing (case 5)', () => {
    const result = validateOnboardingState(
      { ...baseSettings, commercialRegistration: '' },
      { requireOtp: true, otp: '123456' },
    )
    assert.equal(result.valid, false)
    assert.match(result.errors.join(' '), /Commercial Registration/i)
  })

  it('fails when OTP is missing', () => {
    const result = validateOnboardingState(baseSettings, { requireOtp: true, otp: '' })
    assert.equal(result.valid, false)
    assert.match(result.errors.join(' '), /OTP/i)
  })

  it('rejects VAT that does not start and end with 3 (ZATCA TRN format)', () => {
    const result = validateCompanyProfileForZatca(
      { ...baseSettings, taxId: '123456789012345' },
      { requireOtp: true, otp: '123456' },
    )
    assert.equal(result.valid, false)
    assert.match(result.errors.join(' '), /start and end with digit 3/i)
  })
})

describe('mapOnboardingError', () => {
  it('maps invalid OTP (case 2)', () => {
    const mapped = mapOnboardingError(new Error('Invalid-OTP: code rejected'))
    assert.equal(mapped.code, 'INVALID_OTP')
    assert.equal(mapped.httpStatus, 422)
  })

  it('maps expired OTP (case 3)', () => {
    const mapped = mapOnboardingError(new Error('OTP has expired'))
    assert.equal(mapped.code, 'OTP_EXPIRED')
  })

  it('maps invalid CSR (case 6)', () => {
    const mapped = mapOnboardingError(new Error('Invalid-CSR: The provided Certificate Signing Request is invalid'))
    assert.equal(mapped.code, 'INVALID_CSR')
  })

  it('adds production-specific enrollment guidance to Invalid-CSR', () => {
    const mapped = mapOnboardingError(
      new Error('Invalid-CSR: The provided Certificate Signing Request (CSR) is invalid.'),
      { environment: 'PRODUCTION' },
    )
    assert.equal(mapped.code, 'INVALID_CSR')
    assert.match(mapped.message, /Integration wave/i)
    assert.match(mapped.message, /PRODUCTION Fatoora portal/i)
  })

  it('maps API timeout (case 7)', () => {
    const mapped = mapOnboardingError(new Error('fetch failed: ETIMEDOUT'))
    assert.equal(mapped.code, 'API_TIMEOUT')
    assert.equal(mapped.httpStatus, 504)
  })

  it('maps database failure (case 8)', () => {
    const mapped = mapOnboardingError(new Error('PrismaClientKnownRequestError: SQLITE_BUSY'))
    assert.equal(mapped.code, 'DATABASE_FAILURE')
  })

  it('maps duplicate onboarding (case 9)', () => {
    const mapped = mapOnboardingError(new Error('This environment is already onboarded to ZATCA.'))
    assert.equal(mapped.code, 'DUPLICATE_ONBOARDING')
    assert.equal(mapped.httpStatus, 409)
  })
})

describe('connection helpers', () => {
  it('detects already connected credential', () => {
    assert.equal(
      isAlreadyConnected({ onboardingStatus: 'COMPLIANCE_ISSUED' } as never),
      true,
    )
    assert.equal(isAlreadyConnected({ onboardingStatus: 'CSR_GENERATED' } as never), false)
  })

  it('resolves connection label', () => {
    assert.equal(resolveConnectionLabel(true, 'COMPLIANCE_ISSUED'), 'CONNECTED')
    assert.equal(resolveConnectionLabel(false, 'CSR_GENERATED'), 'PENDING')
    assert.equal(resolveConnectionLabel(false, 'NOT_STARTED'), 'NOT_CONNECTED')
    assert.equal(resolveConnectionLabel(false, 'FAILED'), 'FAILED')
  })

  it('preserves valid onboarding status after production CSID failure', () => {
    assert.equal(
      resolveOnboardingStatusAfterProductionFailure('PRODUCTION_ISSUED', true),
      'PRODUCTION_ISSUED',
    )
    assert.equal(
      resolveOnboardingStatusAfterProductionFailure('COMPLIANCE_ISSUED', true),
      'COMPLIANCE_ISSUED',
    )
    assert.equal(
      resolveOnboardingStatusAfterProductionFailure('CSR_GENERATED', false),
      'FAILED',
    )
    assert.equal(
      resolveOnboardingStatusAfterProductionFailure('CSR_GENERATED', true),
      'COMPLIANCE_ISSUED',
    )
  })
})

describe('generateEgsIdentity', () => {
  it('generates automated EGS identity', () => {
    const identity = generateEgsIdentity('Netkom Company', '300000000000003', 'SANDBOX')
    assert.equal(identity.egsUnitId, 'TST-300000000000003')
    assert.ok(identity.deviceIdentifier)
    assert.ok(identity.egsSerialNumber)
  })

  it('multi-company isolation is schema-level (case 10 — single tenant today)', () => {
    const a = generateEgsIdentity('Company A', '300000000000003', 'SANDBOX')
    const b = generateEgsIdentity('Company B', '300000000000004', 'SANDBOX')
    assert.notEqual(a.egsUnitId, b.egsUnitId)
  })
})

describe('verifyZatcaCsr (CSR preflight self-check)', () => {
  it('passes for a CSR that ZATCA actually accepted', () => {
    const result = verifyZatcaCsr(REAL_ACCEPTED_SANDBOX_CSR, {
      environment: 'SANDBOX',
      vat: '311271112900003',
      commonName: 'TST-311271112900003',
    })
    assert.equal(result.ok, true, result.summary)
    assert.equal(result.missingCritical.length, 0)
  })

  it('confirms the template is encoded as PRINTABLESTRING', () => {
    const result = verifyZatcaCsr(REAL_ACCEPTED_SANDBOX_CSR, {
      environment: 'SANDBOX',
      vat: '311271112900003',
      commonName: 'TST-311271112900003',
    })
    const templateField = result.fields.find((f) => f.name.includes('PRINTABLESTRING'))
    assert.ok(templateField?.present)
  })

  it('flags a CSR with no extensions as missing critical fields', () => {
    const empty = '-----BEGIN CERTIFICATE REQUEST-----\nMIIBnQ==\n-----END CERTIFICATE REQUEST-----'
    const result = verifyZatcaCsr(empty, {
      environment: 'PRODUCTION',
      vat: '300000000000003',
      commonName: '300000000000003',
    })
    assert.equal(result.ok, false)
    assert.ok(result.missingCritical.length > 0)
  })
})

describe('successful onboarding (case 1 — mock API contract)', () => {
  it('expects compliance response fields for storage', () => {
    const mockResponse = {
      requestId: 'REQ-1',
      dispositionMessage: 'ISSUED',
      binarySecurityToken: Buffer.from('cert').toString('base64'),
      secret: 'secret',
      certificatePem: '-----BEGIN CERTIFICATE-----\ncert\n-----END CERTIFICATE-----',
    }
    assert.ok(mockResponse.binarySecurityToken)
    assert.ok(mockResponse.secret)
    assert.equal(mockResponse.dispositionMessage, 'ISSUED')
  })
})
